# pylint: disable=missing-module-docstring,unused-import
# coding: utf-8

from __future__ import annotations

import re
from datetime import date, datetime
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, EmailStr, validator


class BadRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BadRequest - a model defined in OpenAPI

        message: The message of this BadRequest [Optional].
    """

    message: Optional[str] = None


BadRequest.update_forward_refs()
