# pylint: disable=missing-module-docstring
# coding: utf-8

from __future__ import annotations

from pydantic import BaseModel


class DumpElements(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DumpElements - a model defined in OpenAPI

        name: The name of this DumpElements.
        reference_type: The reference_type of this DumpElements.
        reference: The reference of this DumpElements.
    """

    name: str
    reference_type: str
    reference: str


DumpElements.update_forward_refs()
