# pylint: disable=missing-module-docstring
# coding: utf-8

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Forbidden(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Forbidden - a model defined in OpenAPI

        message: The message of this Forbidden [Optional].
    """

    message: Optional[str] = None


Forbidden.update_forward_refs()
