# pylint: disable=line-too-long
"""Scientific domains mapping regarding OAG resources"""

# Left side: OAG categories. Right side: MP categories. Keys are mapped into values. Sorted by the values.
scientific_domains_mapping = {
    "natural sciences": "Natural Sciences",
    "sociology": "Social Sciences>Sociology",
    "obstetrics & reproductive medicine": "Medical & Health Sciences>Basic Medicine",
    "agricultural economics & policy": "Agricultural Sciences",
    "health sciences": "Medical & Health Sciences>Health Sciences",
    "tropical medicine": "Medical & Health Sciences>Clinical Medicine",
    "economic theory": "Social Sciences>Economics & Business",
    "mechanical engineering & transports": "Engineering & Technology>Mechanical Engineering",
    "geological & geomatics engineering": "Engineering & Technology",
    "general clinical medicine": "Medical & Health Sciences>Clinical Medicine",
    "art practice": "Humanities>Arts",
    "dairy & animal science": "Agricultural Sciences>Animal & Dairy Sciences",
    "media and communications": "Social Sciences>Media & Communications",
    "sport sciences": "Natural Sciences>Physical Sciences",
    "chemical engineering": "Engineering & Technology>Chemical Engineering",
    "veterinary sciences": "Agricultural Sciences>Veterinary Sciences",
    "social and economic geography": "Social Sciences>Social & Economic Geography",
    "chemical physics": "Natural Sciences>Chemical Sciences",
    "computation theory & mathematics": "Natural Sciences>Mathematics",
    "social sciences methods": "Social Sciences",
    "archaeology": "Humanities>History & Archaeology",
    "other medical science": "Medical & Health Sciences>Other Medical Sciences",
    "ethics and religion": "Humanities>Philosophy, Ethics & Religion",
    "basic medicine": "Medical & Health Sciences>Basic Medicine",
    "electronic engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "environmental biotechnology": "Engineering & Technology>Environmental Biotechnology",
    "industrial biotechnology": "Engineering & Technology>Industrial Biotechnology",
    "history of science": "Social Sciences",
    "agricultural biotechnology": "Agricultural Sciences>Agricultural Biotechnology",
    "psychology and cognitive sciences": "Social Sciences>Psychology",
    "complementary & alternative medicine": "Medical & Health Sciences>Basic Medicine",
    "information & library sciences": "Natural Sciences>Computer & Information Sciences",
    "experimental psychology": "Social Sciences>Psychology",
    "medical engineering": "Engineering & Technology>Medical Engineering",
    "materials": "Engineering & Technology>Materials Engineering",
    "other engineering and technologies": "Engineering & Technology>Other Engineering & Technology Sciences",
    "biotechnology": "Medical & Health Sciences>Medical Biotechnology",
    "developmental & child psychology": "Social Sciences>Psychology",
    "environmental sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "history of social sciences": "Social Sciences",
    "industrial engineering & automation": "Engineering & Technology",
    "languages & linguistics": "Humanities>Languages & Literature",
    "numerical & computational mathematics": "Natural Sciences>Mathematics",
    "physical sciences": "Natural Sciences>Physical Sciences",
    "science studies": "Social Sciences",
    "behavioral science & comparative psychology": "Social Sciences>Psychology",
    "economics and business": "Social Sciences>Economics & Business",
    "social work": "Social Sciences>Sociology",
    "history and archaeology": "Humanities>History & Archaeology",
    "earth and related environmental sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "electrical engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "law": "Social Sciences>Law",
    "computer and information sciences": "Natural Sciences>Computer & Information Sciences",
    "social psychology": "Social Sciences>Psychology",
    "food science": "Medical & Health Sciences>Health Sciences",
    "automobile design & engineering": "Engineering & Technology",
    "environmental engineering": "Engineering & Technology>Environmental Engineering",
    "general mathematics": "Natural Sciences>Mathematics",
    "other agricultural sciences": "Agricultural Sciences>Other Agricultural Sciences",
    "clinical psychology": "Social Sciences>Psychology",
    "political science": "Social Sciences>Political Sciences",
    "legal & forensic medicine": "Medical & Health Sciences>Basic Medicine",
    "health policy & services": "Medical & Health Sciences>Health Sciences",
    "medical and health sciences": "Medical & Health Sciences",
    "nano-technology": "Engineering & Technology",
    "public health": "Medical & Health Sciences>Health Sciences",
    "business & management": "Social Sciences>Economics & Business",
    "animal and dairy science": "Agricultural Sciences>Animal & Dairy Sciences",
    "engineering and technology": "Engineering & Technology",
    "mathematics": "Natural Sciences>Mathematics",
    "communication & media studies": "Social Sciences>Media & Communications",
    "social sciences": "Social Sciences",
    "history": "Humanities>History & Archaeology",
    "languages and literature": "Humanities>Languages & Literature",
    "political science & public administration": "Social Sciences>Political Sciences",
    "veterinary science": "Agricultural Sciences>Veterinary Sciences",
    "general psychology & cognitive sciences": "Social Sciences>Psychology",
    "nuclear medicine & medical imaging": "Medical & Health Sciences>Other Medical Sciences",
    "applied mathematics": "Natural Sciences>Mathematics",
    "economics": "Social Sciences>Economics & Business",
    "agricultural and veterinary sciences": "Agricultural Sciences>Other Agricultural Sciences",
    "philosophy": "Humanities>Philosophy, Ethics & Religion",
    "biological sciences": "Natural Sciences>Biological Sciences",
    "industrial relations": "Engineering & Technology>Industrial Biotechnology",
    "physical chemistry": "Natural Sciences>Physical Sciences",
    "nanoscience & nanotechnology": "Engineering & Technology>Nanotechnology",
    "biomedical engineering": "Engineering & Technology>Medical Engineering",
    "agriculture, forestry, and fisheries": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "other social sciences": "Social Sciences>Other Social Sciences",
    "chemical sciences": "Natural Sciences>Chemical Sciences",
    "clinical medicine": "Medical & Health Sciences>Clinical Medicine",
    "speech-language pathology & audiology": "Humanities>Languages & Literature",
    "mechanical engineering": "Engineering & Technology>Mechanical Engineering",
    "humanities and the arts": "Humanities>Arts",
    "environmental & occupational health": "Natural Sciences>Earth & Related Environmental Sciences",
    "emergency & critical care medicine": "Medical & Health Sciences>Basic Medicine",
    "general & internal medicine": "Medical & Health Sciences>Basic Medicine",
    "arts": "Humanities>Arts",
    "materials engineering": "Engineering & Technology>Materials Engineering",
    "agriculture": "Agricultural Sciences",
    "geography": "Social Sciences>Social & Economic Geography",
    "civil engineering": "Engineering & Technology>Civil Engineering",
    "marine biology": "Natural Sciences>Biological Sciences",
    "evolutionary biology": "Natural Sciences>Biological Sciences",
    "education": "Social Sciences>Educational Sciences",
    "electrical engineering, electronic engineering, information engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "artificial intelligence & image processing": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "zoology": "Agricultural Sciences>Animal & Dairy Sciences",
    "networking & telecommunications": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "general chemistry": "Natural Sciences>Chemical Sciences",
    "neurology & neurosurgery": "Medical & Health Sciences>Clinical Medicine",
    "developmental biology": "Natural Sciences>Biological Sciences",
    "marine biology & hydrobiology": "Natural Sciences>Biological Sciences",
    "plant biology & botany": "Natural Sciences>Biological Sciences",
    "building & construction": "Engineering & Technology>Civil Engineering",
    "software engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "information systems": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "entomology": "Agricultural Sciences>Other Agricultural Sciences",
    "electrical & electronic engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "oncology & carcinogenesis": "Medical & Health Sciences>Clinical Medicine",
    "general physics": "Natural Sciences>Physical Sciences",
    "organic chemistry": "Natural Sciences>Chemical Sciences",
    "analytical chemistry": "Natural Sciences>Chemical Sciences",
    "applied physics": "Natural Sciences>Physical Sciences",
    "nuclear & particles physics": "Natural Sciences>Physical Sciences",
    "paleontology": "Natural Sciences>Biological Sciences",
    "fluids & plasmas": "Natural Sciences>Chemical Sciences",
    "marketing": "Social Sciences>Economics & Business",
    "geochemistry & geophysics": "Natural Sciences>Earth & Related Environmental Sciences",
    "cardiovascular system & hematology": "Medical & Health Sciences>Clinical Medicine",
    "optics": "Natural Sciences>Physical Sciences",
    "strategic, defence & security studies": "Social Sciences>Political Sciences",
    "agronomy & agriculture": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "statistics & probability": "Natural Sciences>Mathematics",
    "astronomy & astrophysics": "Natural Sciences>Physical Sciences",
    "urban & regional planning": "Social Sciences>Educational Sciences",
    "optoelectronics & photonics": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "microbiology": "Natural Sciences>Biological Sciences",
    "finance": "Social Sciences>Economics & Business",
    "operations research": "Engineering & Technology>Other Engineering & Technology Sciences",
    "psychiatry": "Medical & Health Sciences>Other Medical Sciences",
    "human factors": "Engineering & Technology>Other Engineering & Technology Sciences",
    "computer hardware & architecture": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "logistics & transportation": "Social Sciences>Economics & Business",
    "endocrinology & metabolism": "Medical & Health Sciences>Clinical Medicine",
    "mycology & parasitology": "Natural Sciences>Biological Sciences",
    "meteorology & atmospheric sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "philosophy, ethics and religion": "Humanities>Philosophy, Ethics & Religion",
    "dentistry": "Medical & Health Sciences>Other Medical Sciences",
    "mathematical physics": "Natural Sciences>Physical Sciences",
    "pharmacology & pharmacy": "Medical & Health Sciences>Basic Medicine",
    "gastroenterology & hepatology": "Medical & Health Sciences>Clinical Medicine",
    "rehabilitation": "Medical & Health Sciences>Other Medical Sciences",
    "distributed computing": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "medical informatics": "Natural Sciences>Computer & Information Sciences",
    "acoustics": "Natural Sciences>Physical Sciences",
    "medicinal & biomolecular chemistry": "Natural Sciences>Chemical Sciences",
    "sport, leisure & tourism": "Social Sciences>Other Social Sciences",
    "econometrics": "Social Sciences>Economics & Business",
    "pediatrics": "Medical & Health Sciences>Clinical Medicine",
    "nutrition & dietetics": "Medical & Health Sciences>Health Sciences",
    "biochemistry & molecular biology": "Natural Sciences>Biological Sciences",
    "respiratory system": "Medical & Health Sciences>Basic Medicine",
    "aerospace & aeronautics": "Engineering & Technology>Mechanical Engineering",
    "fisheries": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "energy": "Engineering & Technology>Other Engineering & Technology Sciences",
    "ecology": "Natural Sciences>Biological Sciences",
    "accounting": "Social Sciences>Economics & Business",
    "orthopedics": "Medical & Health Sciences>Clinical Medicine",
    "criminology": "Social Sciences>Law",
    "anthropology": "Social Sciences>Other Social Sciences",
    "forestry": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "ophthalmology & optometry": "Medical & Health Sciences>Clinical Medicine",
    "immunology": "Medical & Health Sciences>Basic Medicine",
    "applied ethics": "Humanities>Philosophy, Ethics & Religion",
    "arthritis & rheumatology": "Medical & Health Sciences>Clinical Medicine",
    "international relations": "Social Sciences>Political Sciences",
    "otorhinolaryngology": "Medical & Health Sciences>Clinical Medicine",
    "cultural studies": "Social Sciences>Other Social Sciences",
    "nursing": "Medical & Health Sciences>Other Medical Sciences",
    "urology & nephrology": "Medical & Health Sciences>Clinical Medicine",
    "dermatology & venereal diseases": "Medical & Health Sciences>Clinical Medicine",
    "bioinformatics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "development studies": "Social Sciences>Economics & Business",
    "ornithology": "Natural Sciences>Biological Sciences",
    "substance abuse": "Medical & Health Sciences>Other Medical Sciences",
    "surgery": "Medical & Health Sciences>Clinical Medicine",
    "gender studies": "Social Sciences>Other Social Sciences",
    "anesthesiology": "Medical & Health Sciences>Clinical Medicine",
    "oceanography": "Natural Sciences>Earth & Related Environmental Sciences",
    "design practice & management": "Social Sciences>Other Social Sciences",
    "mining & metallurgy": "Engineering & Technology>Materials Engineering",
    "religions & theology": "Humanities>Philosophy, Ethics & Religion",
    "music": "Humanities>Arts",
    "history of science, technology & medicine": "Humanities>History & Archaeology",
    "gerontology": "Medical & Health Sciences>Health Sciences",
    "literary studies": "Humanities>Languages & Literature",
    "family studies": "Social Sciences>Other Social Sciences",
    "inorganic & nuclear chemistry": "Natural Sciences>Chemical Sciences",
    "psychoanalysis": "Social Sciences>Psychology",
    "physiology": "Medical & Health Sciences>Basic Medicine",
    "geriatrics": "Medical & Health Sciences>Other Medical Sciences",
    "art practice, history & theory": "Humanities>Arts",
    "polymers": "Engineering & Technology>Materials Engineering",
    "horticulture": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "genetics & heredity": "Natural Sciences>Biological Sciences",
    "geology": "Natural Sciences>Earth & Related Environmental Sciences",
    "classics": "Humanities>Other Humanities",
    "toxicology": "Medical & Health Sciences>Basic Medicine",
    "architecture": "Engineering & Technology>Other Engineering & Technology Sciences",
    "anatomy & morphology": "Medical & Health Sciences>Basic Medicine",
    "virology": "Medical & Health Sciences>Basic Medicine",
    "biophysics": "Natural Sciences>Physical Sciences",
    "epidemiology": "Medical & Health Sciences>Other Medical Sciences",
    "drama & theater": "Humanities>Arts",
}

# Marketplace's scientific domains structure. Parents and their children.
mp_sd_structure = {
    "Agricultural Sciences": [
        "Agricultural Sciences>Agricultural Biotechnology",
        "Agricultural Sciences>Agriculture, Forestry & Fisheries",
        "Agricultural Sciences>Animal & Dairy Sciences",
        "Agricultural Sciences>Other Agricultural Sciences",
        "Agricultural Sciences>Veterinary Sciences",
    ],
    "Engineering & Technology": [
        "Engineering & Technology>Chemical Engineering",
        "Engineering & Technology>Civil Engineering",
        "Engineering & Technology>Electrical, Electronic & Information Engineering",
        "Engineering & Technology>Environmental Biotechnology",
        "Engineering & Technology>Environmental Engineering",
        "Engineering & Technology>Industrial Biotechnology",
        "Engineering & Technology>Materials Engineering",
        "Engineering & Technology>Mechanical Engineering",
        "Engineering & Technology>Medical Engineering",
        "Engineering & Technology>Nanotechnology",
        "Engineering & Technology>Other Engineering & Technology Sciences",
    ],
    "Generic": ["Generic>Generic"],
    "Humanities": [
        "Humanities>Arts",
        "Humanities>History & Archaeology",
        "Humanities>Languages & Literature",
        "Humanities>Other Humanities",
        "Humanities>Philosophy, Ethics & Religion",
    ],
    "Medical & Health Sciences": [
        "Medical & Health Sciences>Basic Medicine",
        "Medical & Health Sciences>Clinical Medicine",
        "Medical & Health Sciences>Health Sciences",
        "Medical & Health Sciences>Medical Biotechnology",
        "Medical & Health Sciences>Other Medical Sciences",
    ],
    "Natural Sciences": [
        "Natural Sciences>Biological Sciences",
        "Natural Sciences>Chemical Sciences",
        "Natural Sciences>Computer & Information Sciences",
        "Natural Sciences>Earth & Related Environmental Sciences",
        "Natural Sciences>Mathematics",
        "Natural Sciences>Other Natural Sciences",
        "Natural Sciences>Physical Sciences",
    ],
    "Other": ["Other>Other"],
    "Social Sciences": [
        "Social Sciences>Economics & Business",
        "Social Sciences>Educational Sciences",
        "Social Sciences>Law",
        "Social Sciences>Media & Communications",
        "Social Sciences>Other Social Sciences",
        "Social Sciences>Political Sciences",
        "Social Sciences>Psychology",
        "Social Sciences>Social & Economic Geography",
        "Social Sciences>Sociology",
    ],
}
