version: '3.9'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ess-local
    environment:
      DATABASE_URI: postgresql+psycopg2://${DB_POSTGRES_USER:-ess}:${DB_POSTGRES_PASSWORD:-ess}@db:5432/${DB_POSTGRES_DB:-ess}
      SOLR_URL: http://solr1:8983/solr/
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      SECRET_KEY: "${SECRET_KEY}"
    depends_on:
      - db
      - solr1
  db:
    image: postgres:14
    ports:
      - "5442:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ess-local
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB:-ess}
      POSTGRES_USER: ${DB_POSTGRES_USER:-ess}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-ess}
  solr1:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
      - ./solr/config/configsets:/configsets
      - ./solr/config/solr.xml:/opt/solr/server/solr/solr.xml
      - ./solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - ess-local
    environment:
      ZK_HOST: zoo1:2181
    depends_on:
      - zoo1
  zoo1:
    image: zookeeper:3.7
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zoo1-data:/data
      - zoo1-datalog:/datalog
    networks:
      - ess-local
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok

volumes:
  db-data:
  solr-data:
  zoo1-data:
  zoo1-datalog:

networks:
  ess-local:
