version: '3.9'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ess-local
    environment:
      DATABASE_URI: postgresql+psycopg2://${DB_POSTGRES_USER:-ess}:${DB_POSTGRES_PASSWORD:-ess}@db:5432/${DB_POSTGRES_DB:-ess}
      SOLR_URL: http://solr:8983/solr/
  db:
    image: postgres:14
    ports:
      - "5442:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ess-local
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB:-ess}
      POSTGRES_USER: ${DB_POSTGRES_USER:-ess}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-ess}
  solr:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    networks:
      - ess-local
    command: solr-precreate ess

volumes:
  db-data:
  solr-data:

networks:
  ess-local:
