[tool.isort]
profile = "black"
src_paths = ["alembic", "app", "tests"]
skip_gitignore = true

[tool.pylint.'messages control']
enable=["useless-suppression"]
# Ignore imports when checking for similarities
ignore-imports=true
# Allow single- and two-character names
good-names-rgxs="^[_a-z][_a-z0-9]?$"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning"]
