"""Define properties name that are used multiple times"""

AUTHOR_NAMES = "author_names"
AUTHOR_PIDS = "author_pids"
AUTHOR = "author"
BEST_ACCESS_RIGHT = "best_access_right"
COUNTRY = "country"
DOCUMENT_TYPE = "document_type"
FOS = "fos"
FUNDER = "funder"
ID = "id"
KEYWORDS = "keywords"
LANGUAGE = "language"
OPEN_ACCESS = "open_access"
PUBLISHER = "publisher"
RESEARCH_COMMUNITY = "research_community"
SDG = "sdg"
SUBJECT = "subject"
TITLE = "title"
TYPE = "type"
URL = "url"
DOI = "doi"
UNIFIED_CATEGORIES = "unified_categories"
DOWNLOADS = "usage_counts_downloads"
VIEWS = "usage_counts_views"
TAG_LIST = "tag_list"
PROJECTS = "projects"
INSTANCE = "instance"
CONTEXT = "context"
PID = "pid"

# Text general
AUTHOR_NAMES_TG = "author_names_tg"
KEYWORDS_TG = "keywords_tg"
TAG_LIST_TG = "tag_list_tg"
