"""Funder mapping"""

funder_mapping = {
    "national_science_center_(ncn)": "National Science Center (NCN)",
    "narodowe centrum nauki (ncn)": "National Science Center (NCN)",
    "narodowe_centrum_badan_i_rozwoju_(ncbr)": "National Centre for Research and Development (NCRD)",
    "narodowe centrum badan i rozwoju (ncbr)": "National Centre for Research and Development (NCRD)",
    "foundation_for_polish_science_(fnp)": "Foundation For Polish Science (FNP)",
    "fundacja na rzecz nauki polskiej (fnp)": "Foundation For Polish Science (FNP)",
    "ministerstwo_edukacji_i_nauki": "Ministry of Education and Science (MEiN)",
    "ministerstwo edukacji i nauki (mein)": "Ministry of Education and Science (MEiN)",
    "ministerstwo edukacji i nauki": "Ministry of Education and Science (MEiN)",
    "agency3": "Ministry of Science and Higher Education (MNiSW)",
    "ministerstwo nauki i szkolnictwa wyzszego (mnisw)": "Ministry of Science and Higher Education (MNiSW)",
    "agency4": "Medical Research Agency (MRA)",
    "agencja badan medycznych (abm)": "Medical Research Agency (MRA)",
    "agency5": "European Commission (EC)",
    "komisja europejska (ke)": "European Commission (EC)",
    "agency6": "European Research Council (ERC)",
    "europejska rada ds. badan naukowych (erbn)": "European Research Council (ERC)",
    "agency7": "United Nations Educational, Scientific and Cultural Organization (UNESCO)",
    "organizacja narodow zjednoczonych do spraw oswiaty, nauki i kultury (unesco)": "United Nations Educational, Scientific and Cultural Organization (UNESCO)",
    "agency8": "Visegrad Fund",
    "miedzynarodowy fundusz wyszehradzki": "Visegrad Fund",
    "agency9": "North Atlantic Treaty Organization (NATO)",
    "organizacja traktatu polnocnoatlantyckiego (nato)": "North Atlantic Treaty Organization (NATO)",
    "agency10": "Max-Planck-Gesellschaft",
    "towarzystwo maxa plancka": "Max-Planck-Gesellschaft",
    "agency11": "International Human Frontier Science Program Organization (HFSPO)",
    "miedzynarodowa organizacja programu human frontier science (hfspo)": "International Human Frontier Science Program Organization (HFSPO)",
    "inne": "Other",
    "other": "Other",
    "uj": "Jagiellonian University",
}
