# pylint: disable=line-too-long, duplicate-code
"""Scientific domains mapping regarding Rodbuk resources"""

# Marketplace's scientific domains structure. Parents and their children.
mp_sd_structure = {
    "Agricultural Sciences": [
        "Agricultural Sciences>Agricultural Biotechnology",
        "Agricultural Sciences>Agriculture, Forestry & Fisheries",
        "Agricultural Sciences>Animal & Dairy Sciences",
        "Agricultural Sciences>Other Agricultural Sciences",
        "Agricultural Sciences>Veterinary Sciences",
    ],
    "Engineering & Technology": [
        "Engineering & Technology>Chemical Engineering",
        "Engineering & Technology>Civil Engineering",
        "Engineering & Technology>Electrical, Electronic & Information Engineering",
        "Engineering & Technology>Environmental Biotechnology",
        "Engineering & Technology>Environmental Engineering",
        "Engineering & Technology>Industrial Biotechnology",
        "Engineering & Technology>Materials Engineering",
        "Engineering & Technology>Mechanical Engineering",
        "Engineering & Technology>Medical Engineering",
        "Engineering & Technology>Nanotechnology",
        "Engineering & Technology>Other Engineering & Technology Sciences",
    ],
    "Generic": ["Generic>Generic"],
    "Humanities": [
        "Humanities>Arts",
        "Humanities>History & Archaeology",
        "Humanities>Languages & Literature",
        "Humanities>Other Humanities",
        "Humanities>Philosophy, Ethics & Religion",
    ],
    "Medical & Health Sciences": [
        "Medical & Health Sciences>Basic Medicine",
        "Medical & Health Sciences>Clinical Medicine",
        "Medical & Health Sciences>Health Sciences",
        "Medical & Health Sciences>Medical Biotechnology",
        "Medical & Health Sciences>Other Medical Sciences",
    ],
    "Natural Sciences": [
        "Natural Sciences>Biological Sciences",
        "Natural Sciences>Chemical Sciences",
        "Natural Sciences>Computer & Information Sciences",
        "Natural Sciences>Earth & Related Environmental Sciences",
        "Natural Sciences>Mathematics",
        "Natural Sciences>Other Natural Sciences",
        "Natural Sciences>Physical Sciences",
    ],
    "Other": ["Other>Other"],
    "Social Sciences": [
        "Social Sciences>Economics & Business",
        "Social Sciences>Educational Sciences",
        "Social Sciences>Law",
        "Social Sciences>Media & Communications",
        "Social Sciences>Other Social Sciences",
        "Social Sciences>Political Sciences",
        "Social Sciences>Psychology",
        "Social Sciences>Social & Economic Geography",
        "Social Sciences>Sociology",
    ],
}

oecd_mapping = {
    11: "Natural Sciences>Mathematics",
    12: "Natural Sciences>Computer & Information Sciences",
    13: "Natural Sciences>Physical Sciences",
    14: "Natural Sciences>Chemical Sciences",
    15: "Natural Sciences>Earth & Related Environmental Sciences",
    16: "Natural Sciences>Biological Sciences",
    17: "Natural Sciences>Other Natural Sciences",
    21: "Engineering & Technology>Civil Engineering",
    22: "Engineering & Technology>Electrical, Electronic & Information Engineering",
    23: "Engineering & Technology>Mechanical Engineering",
    24: "Engineering & Technology>Chemical Engineering",
    25: "Engineering & Technology>Materials Engineering",
    26: "Engineering & Technology>Medical Engineering",
    27: "Engineering & Technology>Environmental Engineering",
    28: "Engineering & Technology>Environmental Biotechnology",
    29: "Engineering & Technology>Industrial Biotechnology",
    210: "Engineering & Technology>Nanotechnology",
    211: "Engineering & Technology>Other Engineering & Technology Sciences",
    31: "Medical & Health Sciences>Basic Medicine",
    32: "Medical & Health Sciences>Clinical Medicine",
    33: "Medical & Health Sciences>Health Sciences",
    34: "Medical & Health Sciences>Medical Biotechnology",
    35: "Medical & Health Sciences>Other Medical Sciences",
    41: "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    42: "Agricultural Sciences>Animal & Dairy Sciences",
    43: "Agricultural Sciences>Veterinary Sciences",
    44: "Agricultural Sciences>Agricultural Biotechnology",
    45: "Agricultural Sciences>Other Agricultural Sciences",
    51: "Social Sciences>Psychology",
    52: "Social Sciences>Economics & Business",
    53: "Social Sciences>Educational Sciences",
    54: "Social Sciences>Sociology",
    55: "Social Sciences>Law",
    56: "Social Sciences>Political Sciences",
    57: "Social Sciences>Social & Economic Geography",
    58: "Social Sciences>Media & Communications",
    59: "Social Sciences>Other Social Sciences",
    61: "Humanities>History & Archaeology",
    62: "Humanities>Languages & Literature",
    63: "Humanities>Philosophy, Ethics & Religion",
    64: "Humanities>Arts",
    65: "Humanities>Other Humanities",
}

# Not used, just for the sake of having a snapshot of a CV that was used initially
oecd_controlled_vocabulary = {
    11: "Natural sciences - Mathematics",
    12: "Natural sciences - Computer and information sciences",
    13: "Natural sciences - Physical sciences",
    14: "Natural sciences - Chemical sciences",
    15: "Natural sciences - Earth and related environmental sciences",
    16: "Natural sciences - Biological sciences",
    17: "Natural sciences - Other natural sciences",
    21: "Engineering and technology - Civil engineering",
    22: "Engineering and technology - Electrical engineering, electronic engineering, information engineering",
    23: "Engineering and technology - Mechanical engineering",
    24: "Engineering and technology - Chemical engineering",
    25: "Engineering and technology - Materials engineering",
    26: "Engineering and technology - Medical engineering",
    27: "Engineering and technology - Environmental engineering",
    28: "Engineering and technology - Environmental biotechnology",
    29: "Engineering and technology - Industrial biotechnology",
    210: "Engineering and technology - Nano-technology",
    211: "Engineering and technology - Other engineering and technologies",
    31: "Medical and health sciences - Basic medicine",
    32: "Medical and health sciences - Clinical medicine",
    33: "Medical and health sciences - Health sciences",
    34: "Medical and health sciences - Health biotechnology",
    35: "Medical and health sciences - Other medical sciences",
    41: "Agricultural sciences - Agriculture, forestry, and fisheries",
    42: "Agricultural sciences - Animal and dairy science",
    43: "Agricultural sciences - Veterinary science",
    44: "Agricultural sciences - Agricultural biotechnology",
    45: "Agricultural sciences - Other agricultural sciences",
    51: "Social sciences - Psychology",
    52: "Social sciences - Economics and business",
    53: "Social sciences - Educational sciences",
    54: "Social sciences - Sociology",
    55: "Social sciences - Law",
    56: "Social sciences - Political science",
    57: "Social sciences - Social and economic geography",
    58: "Social sciences - Media and communications",
    59: "Social sciences - Other social sciences",
    61: "Humanities - History and archaeology",
    62: "Humanities - Languages and literature",
    63: "Humanities - Philosophy, ethics and religion",
    64: "Humanities - Arts (arts, history of arts, performing arts, music)",
    65: "Humanities - Other humanities",
}
