# coding: utf-8

"""
    Search Service

    EOSC Search Service

    The version of the OpenAPI document: 1.0.0-alpha0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from search_service.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Search Service",
    description="EOSC Search Service",
    version="1.0.0-alpha0",
)

app.include_router(DefaultApiRouter)
