version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: itzg/rabbitmq-stomp:latest
    platform: linux/amd64
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "61613:61613"
      - "15672:15672"  # admin interface for rabbitmq admin

volumes:
  db-data:
