version: "3.9"

services:
  api:
    build: ./
    ports:
      - 8080:8080
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./
    command: celery -A app.worker.celery worker --concurrency=4 --loglevel=info
    volumes:
      - ./app:/app
      - ./schemas:/schemas
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  dashboard:
    build: ./
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker

  redis:
    image: redis:7

  rabbitmq:
    image: itzg/rabbitmq-stomp:latest
    platform: linux/amd64
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "61613:61613"
      - "15672:15672"  # admin interface for rabbitmq admin

volumes:
  db-data:
