# pylint: disable=line-too-long, duplicate-code
"""Scientific domains mapping regarding OAG resources"""

# Marketplace's scientific domains structure. Parents and their children.
mp_sd_structure = {
    "Agricultural Sciences": [
        "Agricultural Sciences>Agricultural Biotechnology",
        "Agricultural Sciences>Agriculture, Forestry & Fisheries",
        "Agricultural Sciences>Animal & Dairy Sciences",
        "Agricultural Sciences>Other Agricultural Sciences",
        "Agricultural Sciences>Veterinary Sciences",
    ],
    "Engineering & Technology": [
        "Engineering & Technology>Chemical Engineering",
        "Engineering & Technology>Civil Engineering",
        "Engineering & Technology>Electrical, Electronic & Information Engineering",
        "Engineering & Technology>Environmental Biotechnology",
        "Engineering & Technology>Environmental Engineering",
        "Engineering & Technology>Industrial Biotechnology",
        "Engineering & Technology>Materials Engineering",
        "Engineering & Technology>Mechanical Engineering",
        "Engineering & Technology>Medical Engineering",
        "Engineering & Technology>Nanotechnology",
        "Engineering & Technology>Other Engineering & Technology Sciences",
    ],
    "Generic": ["Generic>Generic"],
    "Humanities": [
        "Humanities>Arts",
        "Humanities>History & Archaeology",
        "Humanities>Languages & Literature",
        "Humanities>Other Humanities",
        "Humanities>Philosophy, Ethics & Religion",
    ],
    "Medical & Health Sciences": [
        "Medical & Health Sciences>Basic Medicine",
        "Medical & Health Sciences>Clinical Medicine",
        "Medical & Health Sciences>Health Sciences",
        "Medical & Health Sciences>Medical Biotechnology",
        "Medical & Health Sciences>Other Medical Sciences",
    ],
    "Natural Sciences": [
        "Natural Sciences>Biological Sciences",
        "Natural Sciences>Chemical Sciences",
        "Natural Sciences>Computer & Information Sciences",
        "Natural Sciences>Earth & Related Environmental Sciences",
        "Natural Sciences>Mathematics",
        "Natural Sciences>Other Natural Sciences",
        "Natural Sciences>Physical Sciences",
    ],
    "Other": ["Other>Other"],
    "Social Sciences": [
        "Social Sciences>Economics & Business",
        "Social Sciences>Educational Sciences",
        "Social Sciences>Law",
        "Social Sciences>Media & Communications",
        "Social Sciences>Other Social Sciences",
        "Social Sciences>Political Sciences",
        "Social Sciences>Psychology",
        "Social Sciences>Social & Economic Geography",
        "Social Sciences>Sociology",
    ],
}

# Left side: OAG categories. Right side: MP categories. Keys are mapped into values. Sorted by the values.
scientific_domains_mapping = {
    "1860s neologisms/historical eras": "Humanities>History & Archaeology",
    "3d printing processes/3d printing": "Engineering & Technology>Other Engineering & Technology Sciences",
    "3d printing/structural engineering": "Engineering & Technology>Civil Engineering",
    "abdominal pain/conditions diagnosed by stool test": "Medical & Health Sciences>Other Medical Sciences",
    "abrahamic religions/sociology": "Social Sciences>Sociology",
    "accelerator physics/laser applications": "Natural Sciences>Physical Sciences",
    "accounting": "Social Sciences>Economics & Business",
    "acetylcholine": "Medical & Health Sciences>Other Medical Sciences",
    "acoustics": "Natural Sciences>Physical Sciences",
    "actuarial science/environmental social science": "Social Sciences>Economics & Business",
    "adhesives/packaging materials": "Engineering & Technology>Other Engineering & Technology Sciences",
    "adolescence/puberty": "Medical & Health Sciences>Other Medical Sciences",
    "adverse childhood experiences/crimes": "Social Sciences>Psychology",
    "aeolis quadrangle": "Natural Sciences>Earth & Related Environmental Sciences",
    "aerodynamics/fluid dynamics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "aerospace & aeronautics": "Engineering & Technology>Mechanical Engineering",
    "agavoideae": "Natural Sciences>Biological Sciences",
    "aging-associated diseases/cognitive disorders": "Medical & Health Sciences>Other Medical Sciences",
    "aging-associated diseases/heart diseases": "Medical & Health Sciences>Other Medical Sciences",
    "agricultural and veterinary sciences": "Agricultural Sciences>Other Agricultural Sciences",
    "agricultural biotechnology": "Agricultural Sciences>Agricultural Biotechnology",
    "agricultural economics & policy": "Agricultural Sciences",
    "agriculture": "Agricultural Sciences",
    "agriculture, forestry, and fisheries": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "agroecology/sustainable agriculture": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "agronomy & agriculture": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "agronomy/crops": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "agronomy/land management": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "air pollution/pollution": "Natural Sciences>Earth & Related Environmental Sciences",
    "allergy": "Medical & Health Sciences>Other Medical Sciences",
    "analytic philosophy/empiricism": "Humanities>Philosophy, Ethics & Religion",
    "alloys/glass": "Engineering & Technology>Materials Engineering",
    "amino acids/chemical articles with multiple compound ids": "Natural Sciences>Chemical Sciences",
    "analytical chemistry": "Natural Sciences>Chemical Sciences",
    "anatomy & morphology": "Medical & Health Sciences>Basic Medicine",
    "anatomy/medical education": "Medical & Health Sciences>Basic Medicine",
    "anesthesia/anesthesiology": "Medical & Health Sciences>Other Medical Sciences",
    "anesthesiology": "Medical & Health Sciences>Clinical Medicine",
    "anglophone-centric": "Humanities>Languages & Literature",
    "animal and dairy science": "Agricultural Sciences>Animal & Dairy Sciences",
    "animal viral diseases/swine diseases": "Medical & Health Sciences>Veterinary Sciences",
    "anthropology": "Social Sciences>Other Social Sciences",
    "antimicrobial resistance/evolutionary biology": "Natural Sciences>Biological Sciences",
    "antiviral drugs/biocides": "Medical & Health Sciences>Other Medical Sciences",
    "anxiety disorders/spoken articles": "Medical & Health Sciences>Other Medical Sciences",
    "apis (genus)/beekeeping": "Agricultural Sciences>Animal & Dairy Sciences",
    "applications of artificial intelligence/assistive technology": "Engineering & Technology>Other Engineering & Technology Sciences",
    "applications of computer vision/computer vision/image processing": "Engineering & Technology>Other Engineering & Technology Sciences",
    "applied ethics": "Humanities>Philosophy, Ethics & Religion",
    "applied linguistics/social media": "Social Sciences>Media & Communications",
    "applied mathematics": "Natural Sciences>Mathematics",
    "applied physics": "Natural Sciences>Physical Sciences",
    "aquaculture/aquaponics": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "archaeological science/art and cultural repatriation": "Humanities>History & Archaeology",
    "archaeology": "Humanities>History & Archaeology",
    "archaeology/methods in archaeology": "Humanities>History & Archaeology",
    "architecture": "Engineering & Technology>Other Engineering & Technology Sciences",
    "art practice": "Humanities>Arts",
    "art practice, history & theory": "Humanities>Arts",
    "arthritis & rheumatology": "Medical & Health Sciences>Clinical Medicine",
    "arthritis/skeletal disorders": "Medical & Health Sciences>Other Medical Sciences",
    "artificial intelligence & image processing": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "artificial intelligence/computational fields of study": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "arts": "Humanities>Arts",
    "asbestos/industrial and organizational psychology": "Social Sciences>Psychology",
    "asthma/chronic lower respiratory diseases": "Medical & Health Sciences>Other Medical Sciences",
    "astrochemistry/chemistry": "Natural Sciences>Chemical Sciences",
    "astronomy & astrophysics": "Natural Sciences>Physical Sciences",
    "audiology/hearing": "Medical & Health Sciences>Other Medical Sciences",
    "audiology/otology": "Medical & Health Sciences>Other Medical Sciences",
    "auditing/accounting terminology": "Social Sciences>Economics & Business",
    "auditing/types of auditing": "Social Sciences>Economics & Business",
    "autism spectrum disorders/learning disabilities": "Medical & Health Sciences>Other Medical Sciences",
    "autocorrelation/signal processing": "Engineering & Technology>Other Engineering & Technology Sciences",
    "autoimmune diseases/inflammations": "Medical & Health Sciences>Other Medical Sciences",
    "autoimmune diseases/multiple sclerosis": "Medical & Health Sciences>Other Medical Sciences",
    "autoimmune diseases/rheumatology": "Medical & Health Sciences>Other Medical Sciences",
    "automation software/robotics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "automobile design & engineering": "Engineering & Technology",
    "bacteriology/bacteria": "Natural Sciences>Biological Sciences",
    "banks/banking terms": "Social Sciences>Economics & Business",
    "bariatrics/digestive system surgery": "Medical & Health Sciences>Other Medical Sciences",
    "basic medicine": "Medical & Health Sciences>Basic Medicine",
    "behavior": "Social Sciences>Psychology",
    "behavioral addiction/sexual dysfunctions": "Social Sciences>Psychology",
    "behavioral science & comparative psychology": "Social Sciences>Psychology",
    "behaviorism/behavior modification": "Social Sciences>Psychology",
    "behavioural sciences/cognitive psychology": "Social Sciences>Psychology",
    "biochemistry & molecular biology": "Natural Sciences>Biological Sciences",
    "bioethics": "Humanities>Philosophy, Ethics & Religion",
    "biofuels/biodegradable waste management": "Engineering & Technology>Environmental Biotechnology",
    "biogeography/former supercontinents": "Natural Sciences>Earth & Related Environmental Sciences",
    "bioinformatics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "biological oceanography/marine biology": "Natural Sciences>Biological Sciences",
    "biological pest control/entomology": "Natural Sciences>Biological Sciences",
    "biological pest control/insects in culture": "Natural Sciences>Biological Sciences",
    "biological sciences": "Natural Sciences>Biological Sciences",
    "biomarkers/biotechnology": "Natural Sciences>Biological Sciences",
    "biomarkers/stool tests": "Medical & Health Sciences>Other Medical Sciences",
    "biomass/biofuels/bioenergy": "Engineering & Technology>Environmental Biotechnology",
    "biomechanics/motor control": "Medical & Health Sciences>Other Medical Sciences",
    "biomedical engineering": "Engineering & Technology>Medical Engineering",
    "biometrics/authentication methods": "Natural Sciences>Computer & Information Sciences",
    "biophysics": "Natural Sciences>Physical Sciences",
    "biosensors/nanomedicine": "Medical & Health Sciences>Other Medical Sciences",
    "biotechnology": "Medical & Health Sciences>Medical Biotechnology",
    "blood pressure": "Medical & Health Sciences>Other Medical Sciences",
    "bone fractures/acute pain": "Medical & Health Sciences>Other Medical Sciences",
    "botany/herbalism": "Natural Sciences>Biological Sciences",
    "boundary value problems/boundary conditions": "Natural Sciences>Mathematics",
    "brain/neural circuits": "Medical & Health Sciences>Other Medical Sciences",
    "brand management/branding terminology": "Social Sciences>Economics & Business",
    "breast cancer/antineoplastic drugs": "Medical & Health Sciences>Other Medical Sciences",
    "breast surgery/cosmetic surgery": "Medical & Health Sciences>Other Medical Sciences",
    "brewing/fermented drinks": "Agricultural Sciences>Other Agricultural Sciences",
    "building & construction": "Engineering & Technology>Civil Engineering",
    "building engineering/construction and extraction occupations": "Engineering & Technology>Civil Engineering",
    "building materials/concrete": "Engineering & Technology>Materials Engineering",
    "burns/acute pain": "Medical & Health Sciences>Other Medical Sciences",
    "business & management": "Social Sciences>Economics & Business",
    "business cycle": "Social Sciences>Economics & Business",
    "capitalism/comparative politics": "Social Sciences>Economics & Business",
    "car culture/commuting": "Engineering & Technology>Other Engineering & Technology Sciences",
    "carbohydrate chemistry/carbohydrates": "Natural Sciences>Chemical Sciences",
    "carbon cycle/chemical oceanography": "Natural Sciences>Earth & Related Environmental Sciences",
    "carbon dioxide/gas technologies": "Engineering & Technology>Other Engineering & Technology Sciences",
    "cardiac imaging/medical imaging": "Medical & Health Sciences>Other Medical Sciences",
    "cardiovascular physiology/human anatomy by organ": "Medical & Health Sciences>Other Medical Sciences",
    "cardiovascular system & hematology": "Medical & Health Sciences>Clinical Medicine",
    "caregiving/hospice": "Medical & Health Sciences>Other Medical Sciences",
    "casting (manufacturing)/metallurgical processes": "Engineering & Technology>Materials Engineering",
    "catalysis": "Natural Sciences>Chemical Sciences",
    "catalysis/chemical engineering": "Natural Sciences>Chemical Sciences",
    "catalysis/chemical processes": "Natural Sciences>Chemical Sciences",
    "catalysis/industrial processes": "Natural Sciences>Chemical Sciences",
    "cellulose/polysaccharides": "Natural Sciences>Chemical Sciences",
    "centuries/decades": "Other>Other",
    "chalcogenides/optical materials": "Natural Sciences>Physical Sciences",
    "checklists/health care quality": "Medical & Health Sciences>Other Medical Sciences",
    "chemical elements/nuclear materials": "Natural Sciences>Chemical Sciences",
    "chemical engineering": "Engineering & Technology>Chemical Engineering",
    "chemical physics": "Natural Sciences>Chemical Sciences",
    "chemical sciences": "Natural Sciences>Chemical Sciences",
    "chemical synthesis/organic synthesis": "Natural Sciences>Chemical Sciences",
    "chemical synthesis/total synthesis": "Natural Sciences>Chemical Sciences",
    "chemistry/chemical industry": "Natural Sciences>Chemical Sciences",
    "chemistry/lists of chemical elements": "Natural Sciences>Chemical Sciences",
    "childhood/developmental psychology": "Social Sciences>Psychology",
    "childhood/pediatrics": "Medical & Health Sciences>Other Medical Sciences",
    "chimpanzees/iucn red list endangered species": "Natural Sciences>Biological Sciences",
    "civil engineering": "Engineering & Technology>Civil Engineering",
    "classical mechanics stubs/continuum mechanics": "Engineering & Technology>Mechanical Engineering",
    "classics": "Humanities>Other Humanities",
    "clay minerals group/phyllosilicates": "Natural Sciences>Earth & Related Environmental Sciences",
    "climate change policy/ethanol fuel": "Engineering & Technology>Environmental Engineering",
    "climatology": "Natural Sciences>Earth & Related Environmental Sciences",
    "clinical medicine": "Medical & Health Sciences>Clinical Medicine",
    "clinical pathology/health care occupations": "Medical & Health Sciences>Other Medical Sciences",
    "clinical psychology": "Social Sciences>Psychology",
    "clinical research/design of experiments": "Medical & Health Sciences>Other Medical Sciences",
    "clothing industry/technical fabrics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "coal/environmental impact of the coal industry": "Natural Sciences>Earth & Related Environmental Sciences",
    "cognition/motivation": "Social Sciences>Psychology",
    "cognition/neuropsychological assessment": "Social Sciences>Psychology",
    "combustion/fire": "Engineering & Technology>Other Engineering & Technology Sciences",
    "commercial fish/fish common names": "Natural Sciences>Biological Sciences",
    "communication & media studies": "Social Sciences>Media & Communications",
    "complementary & alternative medicine": "Medical & Health Sciences>Basic Medicine",
    "complex systems theory/computational fields of study": "Engineering & Technology>Other Engineering & Technology Sciences",
    "composite materials/fibers": "Engineering & Technology>Materials Engineering",
    "composite materials/fibre-reinforced polymers": "Engineering & Technology>Materials Engineering",
    "composite materials/vehicle armour": "Engineering & Technology>Materials Engineering",
    "computation theory & mathematics": "Natural Sciences>Mathematics",
    "computational chemistry/molecular modelling": "Natural Sciences>Chemical Sciences",
    "computational chemistry/theoretical chemistry": "Natural Sciences>Chemical Sciences",
    "computational fields of study/fractional calculus": "Engineering & Technology>Other Engineering & Technology Sciences",
    "computational problems in graph theory/np-complete problems": "Natural Sciences>Computer & Information Sciences",
    "computer and information sciences": "Natural Sciences>Computer & Information Sciences",
    "computer hardware & architecture": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "computer memory/emerging technologies": "Engineering & Technology>Other Engineering & Technology Sciences",
    "computing output devices/haptic technology": "Engineering & Technology>Other Engineering & Technology Sciences",
    "concepts in astronomy/galaxies": "Natural Sciences>Physical Sciences",
    "concepts in metaphysics/causality": "Humanities>Philosophy, Ethics & Religion",
    "concrete/building materials": "Engineering & Technology>Materials Engineering",
    "concrete/concrete buildings and structures": "Engineering & Technology>Materials Engineering",
    "concurrency (computer science)/debugging": "Natural Sciences>Computer & Information Sciences",
    "conditions diagnosed by stool test/diarrhea": "Medical & Health Sciences>Other Medical Sciences",
    "conflict (process)/crimes against women": "Social Sciences>Criminology",
    "construction/building engineering": "Engineering & Technology>Civil Engineering",
    "continents/europe": "Natural Sciences>Earth & Related Environmental Sciences",
    "continuum mechanics/thermodynamics": "Engineering & Technology>Mechanical Engineering",
    "control theory/advanced driver assistance systems": "Engineering & Technology>Other Engineering & Technology Sciences",
    "corporate finance/corporate governance": "Social Sciences>Economics & Business",
    "corporate governance/corporate social responsibility": "Social Sciences>Economics & Business",
    "corrosion/coatings": "Engineering & Technology>Materials Engineering",
    "crewed spacecraft/astrodynamics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "crewed spacecraft/embedded systems": "Engineering & Technology>Other Engineering & Technology Sciences",
    "crime by type/criminology": "Social Sciences>Criminology",
    "criminology": "Social Sciences>Law",
    "criminology/psychopathy": "Social Sciences>Criminology",
    "cross-platform free software/dynamic programming languages": "Natural Sciences>Computer & Information Sciences",
    "cryptography/information governance": "Natural Sciences>Computer & Information Sciences",
    "cultural studies": "Social Sciences>Other Social Sciences",
    "culture/religion": "Social Sciences>Sociology",
    "cutaneous conditions/autoimmune diseases": "Medical & Health Sciences>Other Medical Sciences",
    "cystic fibrosis/lung disorders": "Medical & Health Sciences>Other Medical Sciences",
    "dairy & animal science": "Agricultural Sciences>Animal & Dairy Sciences",
    "dairy farming/milk": "Agricultural Sciences>Animal & Dairy Sciences",
    "dairy products/milk": "Agricultural Sciences>Animal & Dairy Sciences",
    "dark matter/physical cosmology": "Natural Sciences>Physical Sciences",
    "data management/big data": "Natural Sciences>Computer & Information Sciences",
    "dental materials/restorative dentistry": "Medical & Health Sciences>Other Medical Sciences",
    "dentistry": "Medical & Health Sciences>Other Medical Sciences",
    "dentistry occupations/dentistry": "Medical & Health Sciences>Other Medical Sciences",
    "dermatology & venereal diseases": "Medical & Health Sciences>Clinical Medicine",
    "design of experiments/clinical research": "Medical & Health Sciences>Other Medical Sciences",
    "design practice & management": "Social Sciences>Other Social Sciences",
    "development studies": "Social Sciences>Economics & Business",
    "developmental & child psychology": "Social Sciences>Psychology",
    "developmental biology": "Natural Sciences>Biological Sciences",
    "diabetes/insulin therapies": "Medical & Health Sciences>Other Medical Sciences",
    "diarrhea/conditions diagnosed by stool test": "Medical & Health Sciences>Other Medical Sciences",
    "dietary supplements/nutrition by type": "Medical & Health Sciences>Other Medical Sciences",
    "diets/food and the environment": "Medical & Health Sciences>Other Medical Sciences",
    "digenea/disease ecology": "Natural Sciences>Biological Sciences",
    "digestive system surgery/surgery": "Medical & Health Sciences>Other Medical Sciences",
    "discourse analysis/semantics": "Humanities>Languages & Literature",
    "distributed computing": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "distributed computing/computability theory": "Natural Sciences>Computer & Information Sciences",
    "domesticated animals/livestock": "Agricultural Sciences>Animal & Dairy Sciences",
    "drama & theater": "Humanities>Arts",
    "drinking culture/alcohol abuse": "Medical & Health Sciences>Other Medical Sciences",
    "drug delivery devices": "Medical & Health Sciences>Other Medical Sciences",
    "drug discovery/clinical research": "Medical & Health Sciences>Other Medical Sciences",
    "drug discovery/health policy": "Medical & Health Sciences>Other Medical Sciences",
    "drugs that are a vaccine": "Medical & Health Sciences>Other Medical Sciences",
    "dynamical systems/complex systems theory": "Engineering & Technology>Other Engineering & Technology Sciences",
    "dynamical systems/nonlinear systems": "Engineering & Technology>Other Engineering & Technology Sciences",
    "e-learning/education and training occupations": "Social Sciences>Educational Sciences",
    "earth and related environmental sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "earth sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "eating disorders/culture-bound syndromes": "Medical & Health Sciences>Other Medical Sciences",
    "ecological restoration/forests": "Natural Sciences>Earth & Related Environmental Sciences",
    "ecology": "Natural Sciences>Biological Sciences",
    "ecology/concepts in epistemology": "Natural Sciences>Biological Sciences",
    "econometrics": "Social Sciences>Economics & Business",
    "economic bubbles/financial crises": "Social Sciences>Economics & Business",
    "economic country classifications/international development": "Social Sciences>Economics & Business",
    "economic theory": "Social Sciences>Economics & Business",
    "economics": "Social Sciences>Economics & Business",
    "economics and business": "Social Sciences>Economics & Business",
    "edible nuts and seeds/fagus": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "education": "Social Sciences>Educational Sciences",
    "education and training occupations/career advice services": "Social Sciences>Educational Sciences",
    "educational practices/oxbridge": "Social Sciences>Educational Sciences",
    "educational stages/school types": "Social Sciences>Educational Sciences",
    "educational stages/undergraduate education": "Social Sciences>Educational Sciences",
    "educational technology/learning": "Social Sciences>Educational Sciences",
    "electric motors/energy conversion": "Engineering & Technology>Other Engineering & Technology Sciences",
    "electric motors/machines": "Engineering & Technology>Other Engineering & Technology Sciences",
    "electric power distribution/electrical grid/distributed generation": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electric power/electronics and the environment": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electrical & electronic engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electrical engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electrical engineering, electronic engineering, information engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electrical grid/control theory": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electrochemistry/electrolysis": "Natural Sciences>Chemical Sciences",
    "electronic engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "electroweak theory/quantum field theory": "Natural Sciences>Physical Sciences",
    "emergency & critical care medicine": "Medical & Health Sciences>Basic Medicine",
    "emergency medicine/hospital departments": "Medical & Health Sciences>Other Medical Sciences",
    "emerging technologies/jet engines": "Engineering & Technology>Other Engineering & Technology Sciences",
    "emerging technologies/quantum information science": "Engineering & Technology>Nanotechnology",
    "emerging technologies/robotics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "emotion/affective science": "Social Sciences>Psychology",
    "endocrine-related cutaneous conditions/neuroendocrinology": "Medical & Health Sciences>Other Medical Sciences",
    "endocrinology & metabolism": "Medical & Health Sciences>Clinical Medicine",
    "endodontics/dental equipment": "Medical & Health Sciences>Other Medical Sciences",
    "endodontics/dentistry": "Medical & Health Sciences>Other Medical Sciences",
    "endoscopy/diagnostic gastroenterology": "Medical & Health Sciences>Other Medical Sciences",
    "energy": "Engineering & Technology>Other Engineering & Technology Sciences",
    "energy policy/renewable energy commercialization/renewable energy": "Engineering & Technology>Other Engineering & Technology Sciences",
    "engineering and technology": "Engineering & Technology",
    "engineering disciplines/marine engineering": "Engineering & Technology>Other Engineering & Technology Sciences",
    "engineering disciplines/systems engineering": "Engineering & Technology>Other Engineering & Technology Sciences",
    "engines/energy conversion": "Engineering & Technology>Other Engineering & Technology Sciences",
    "english-language idioms/sexual selection": "Social Sciences>Other Social Sciences",
    "entomology": "Agricultural Sciences>Other Agricultural Sciences",
    "entrepreneurship/business occupations": "Social Sciences>Economics & Business",
    "environmental & occupational health": "Natural Sciences>Earth & Related Environmental Sciences",
    "environmental biotechnology": "Engineering & Technology>Environmental Biotechnology",
    "environmental engineering": "Engineering & Technology>Environmental Engineering",
    "environmental sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "environmental social science concepts/environmental terminology": "Social Sciences>Other Social Sciences",
    "environmental social science concepts/systems ecology": "Natural Sciences>Earth & Related Environmental Sciences",
    "environmental social science/health promotion": "Social Sciences>Other Social Sciences",
    "enzymes/metabolism": "Natural Sciences>Biological Sciences",
    "epidemiology": "Medical & Health Sciences>Other Medical Sciences",
    "epistemological theories/reasoning": "Humanities>Philosophy, Ethics & Religion",
    "ergonomics/occupational safety and health": "Engineering & Technology>Other Engineering & Technology Sciences",
    "ethanol fuel/engine fuel system technology/emission standards": "Engineering & Technology>Environmental Engineering",
    "ethical consumerism/sustainable development": "Social Sciences>Other Social Sciences",
    "ethics and religion": "Humanities>Philosophy, Ethics & Religion",
    "ethnic and religious slurs/lists of pejorative terms for people": "Social Sciences>Other Social Sciences",
    "ethnic groups/ethnicity": "Social Sciences>Other Social Sciences",
    "evidence-based practices/information science": "Natural Sciences>Computer & Information Sciences",
    "evolutionary algorithms/cybernetics/mathematical optimization": "Natural Sciences>Mathematics",
    "evolutionary biology": "Natural Sciences>Biological Sciences",
    "exoplanets discovered by the kepler space telescope/transiting exoplanets": "Natural Sciences>Physical Sciences",
    "experimental psychology": "Social Sciences>Psychology",
    "extant hettangian first appearances/lizards": "Natural Sciences>Biological Sciences",
    "eyewitness/memory": "Social Sciences>Psychology",
    "family studies": "Social Sciences>Other Social Sciences",
    "family/interpersonal relationships": "Social Sciences>Other Social Sciences",
    "feminist terminology/gender roles": "Social Sciences>Sociology",
    "fertility medicine/fertility": "Medical & Health Sciences>Other Medical Sciences",
    "fiber optics/optical fiber": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fiber-optic communications/fiber optics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fiber-optic communications/optical communications": "Engineering & Technology>Other Engineering & Technology Sciences",
    "finance": "Social Sciences>Economics & Business",
    "finance stubs/sales taxes": "Social Sciences>Economics & Business",
    "fire protection/building engineering": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fiscal policy/public finance": "Social Sciences>Economics & Business",
    "fisheries": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "fluid dynamics/aerodynamics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fluids & plasmas": "Natural Sciences>Chemical Sciences",
    "food safety/food science": "Medical & Health Sciences>Other Medical Sciences",
    "food safety/foodborne illnesses": "Medical & Health Sciences>Other Medical Sciences",
    "food science": "Medical & Health Sciences>Health Sciences",
    "food science/food industry": "Medical & Health Sciences>Other Medical Sciences",
    "foodborne illnesses/helminthiases": "Medical & Health Sciences>Other Medical Sciences",
    "force/classical mechanics": "Engineering & Technology>Mechanical Engineering",
    "forensic disciplines/forensic science": "Social Sciences>Other Social Sciences",
    "forestry": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "forests/ecosystems": "Natural Sciences>Earth & Related Environmental Sciences",
    "forests/habitats": "Natural Sciences>Earth & Related Environmental Sciences",
    "forests/trees": "Natural Sciences>Earth & Related Environmental Sciences",
    "forms of water/cryosphere": "Natural Sciences>Earth & Related Environmental Sciences",
    "fractional calculus/dynamical systems": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fractional calculus/equations": "Natural Sciences>Mathematics",
    "fracture mechanics/materials degradation": "Engineering & Technology>Materials Engineering",
    "fuel cells": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fuel cells/hydrogen economy": "Engineering & Technology>Other Engineering & Technology Sciences",
    "functional groups/ethers": "Natural Sciences>Chemical Sciences",
    "functional groups/tuberculosis": "Medical & Health Sciences>Other Medical Sciences",
    "fungal diseases/aspergillus": "Medical & Health Sciences>Other Medical Sciences",
    "fusion power/tokamaks": "Engineering & Technology>Other Engineering & Technology Sciences",
    "fuzzy logic/artificial neural networks/computational neuroscience": "Engineering & Technology>Other Engineering & Technology Sciences",
    "gambling and society/online gambling": "Social Sciences>Other Social Sciences",
    "gastroenterology & hepatology": "Medical & Health Sciences>Clinical Medicine",
    "gender studies": "Social Sciences>Other Social Sciences",
    "general & internal medicine": "Medical & Health Sciences>Basic Medicine",
    "general chemistry": "Natural Sciences>Chemical Sciences",
    "general clinical medicine": "Medical & Health Sciences>Clinical Medicine",
    "general mathematics": "Natural Sciences>Mathematics",
    "general physics": "Natural Sciences>Physical Sciences",
    "general psychology & cognitive sciences": "Social Sciences>Psychology",
    "genetics & heredity": "Natural Sciences>Biological Sciences",
    "genomics/bioinformatics": "Natural Sciences>Biological Sciences",
    "geochemistry & geophysics": "Natural Sciences>Earth & Related Environmental Sciences",
    "geographic data and information/geographic information systems": "Natural Sciences>Earth & Related Environmental Sciences",
    "geography": "Social Sciences>Social & Economic Geography",
    "geography/cultural geography": "Natural Sciences>Earth & Related Environmental Sciences",
    "geological & geomatics engineering": "Engineering & Technology",
    "geology": "Natural Sciences>Earth & Related Environmental Sciences",
    "geomagnetism/ionosphere": "Natural Sciences>Physical Sciences",
    "geometry": "Natural Sciences>Mathematics",
    "geriatrics": "Medical & Health Sciences>Other Medical Sciences",
    "gerontology": "Medical & Health Sciences>Health Sciences",
    "gerontology/old age": "Social Sciences>Other Social Sciences",
    "gifted education/educational psychology": "Social Sciences>Educational Sciences",
    "glass compositions/glass": "Engineering & Technology>Materials Engineering",
    "governance/political science terminology": "Social Sciences>Political Sciences",
    "graphic design/communication design": "Humanities>Arts",
    "group processes/collective identity": "Social Sciences>Other Social Sciences",
    "growth hormones/human female reproductive system": "Medical & Health Sciences>Other Medical Sciences",
    "gynaecological cancer/oncology": "Medical & Health Sciences>Other Medical Sciences",
    "halal food/food law": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "health care occupations": "Medical & Health Sciences>Other Medical Sciences",
    "health care quality/health care": "Medical & Health Sciences>Other Medical Sciences",
    "health care/health care quality": "Medical & Health Sciences>Other Medical Sciences",
    "health economics/health policy": "Social Sciences>Economics & Business",
    "health informatics/electronic health records": "Natural Sciences>Computer & Information Sciences",
    "health issues in pregnancy/midwifery": "Medical & Health Sciences>Other Medical Sciences",
    "health policy & services": "Medical & Health Sciences>Health Sciences",
    "health sciences": "Medical & Health Sciences>Health Sciences",
    "hearing loss/audiology": "Medical & Health Sciences>Other Medical Sciences",
    "heat transfer/heat conduction": "Engineering & Technology>Other Engineering & Technology Sciences",
    "heat transfer/heat exchangers": "Engineering & Technology>Other Engineering & Technology Sciences",
    "heat transfer/thermodynamics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "heating, ventilation, and air conditioning/heat transfer": "Engineering & Technology>Other Engineering & Technology Sciences",
    "hematology/coagulopathies": "Medical & Health Sciences>Other Medical Sciences",
    "hepatology/biliary tract disorders": "Medical & Health Sciences>Other Medical Sciences",
    "historical eras/extinction events": "Natural Sciences>Earth & Related Environmental Sciences",
    "historical eras/paleolithic": "Natural Sciences>Earth & Related Environmental Sciences",
    "historiography/philosophy of history": "Humanities>Philosophy, Ethics & Religion",
    "history": "Humanities>History & Archaeology",
    "history and archaeology": "Humanities>History & Archaeology",
    "history of science": "Social Sciences",
    "history of science, technology & medicine": "Humanities>History & Archaeology",
    "history of social sciences": "Social Sciences",
    "holocene": "Natural Sciences>Earth & Related Environmental Sciences",
    "holography/black holes": "Natural Sciences>Physical Sciences",
    "horse anatomy/horse management": "Agricultural Sciences>Animal & Dairy Sciences",
    "horticulture": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "horticulture/soil": "Agricultural Sciences>Other Agricultural Sciences",
    "human eye anatomy/blindness": "Medical & Health Sciences>Other Medical Sciences",
    "human factors": "Engineering & Technology>Other Engineering & Technology Sciences",
    "human geography/geography": "Natural Sciences>Earth & Related Environmental Sciences",
    "human life stages/human development": "Social Sciences>Other Social Sciences",
    "humanities and the arts": "Humanities>Arts",
    "human–computer interaction": "Natural Sciences>Computer & Information Sciences",
    "hydraulic fracturing/structural geology": "Natural Sciences>Earth & Related Environmental Sciences",
    "hydrology/hydraulic engineering": "Engineering & Technology>Environmental Engineering",
    "hydrology/water": "Engineering & Technology>Environmental Engineering",
    "hydrology/water and the environment": "Engineering & Technology>Environmental Engineering",
    "hypertension/pulmonary heart disease and diseases of pulmonary circulation": "Medical & Health Sciences>Other Medical Sciences",
    "immigration/human migration": "Social Sciences>Sociology",
    "immune system/human cells": "Medical & Health Sciences>Other Medical Sciences",
    "immunology": "Medical & Health Sciences>Basic Medicine",
    "implants (medicine)/prosthetics": "Medical & Health Sciences>Other Medical Sciences",
    "industrial biotechnology": "Engineering & Technology>Industrial Biotechnology",
    "industrial engineering & automation": "Engineering & Technology",
    "industrial relations": "Engineering & Technology>Industrial Biotechnology",
    "industrialisation/industrial engineering": "Engineering & Technology>Other Engineering & Technology Sciences",
    "infectious causes of cancer/digestive system neoplasia": "Medical & Health Sciences>Other Medical Sciences",
    "inflammations/kidney diseases": "Medical & Health Sciences>Other Medical Sciences",
    "information & library sciences": "Natural Sciences>Computer & Information Sciences",
    "information systems": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "information systems/innovation": "Natural Sciences>Computer & Information Sciences",
    "information systems/recommender systems": "Natural Sciences>Computer & Information Sciences",
    "information theory/wireless networking": "Natural Sciences>Computer & Information Sciences",
    "innovation/product management": "Social Sciences>Economics & Business",
    "inorganic & nuclear chemistry": "Natural Sciences>Chemical Sciences",
    "insect pests of millets/spodoptera": "Agricultural Sciences>Other Agricultural Sciences",
    "insect vectors of human pathogens/malaria": "Medical & Health Sciences>Other Medical Sciences",
    "intellectual disability/neurodevelopmental disorders": "Medical & Health Sciences>Other Medical Sciences",
    "intensive care medicine/hospital departments": "Medical & Health Sciences>Other Medical Sciences",
    "international business/international trade": "Social Sciences>Economics & Business",
    "international relations": "Social Sciences>Political Sciences",
    "international relations/globalization": "Social Sciences>Political Sciences",
    "interpersonal relationships/sexual fidelity": "Social Sciences>Sociology",
    "intimate partner violence/abuse": "Social Sciences>Sociology",
    "ionic liquids/ions": "Natural Sciences>Chemical Sciences",
    "iucn red list least concern species/holarctic fauna": "Natural Sciences>Biological Sciences",
    "iucn red list least concern species/larus": "Natural Sciences>Biological Sciences",
    "joints/upper limb anatomy": "Medical & Health Sciences>Other Medical Sciences",
    "kidney diseases/organ failure": "Medical & Health Sciences>Other Medical Sciences",
    "language acquisition/bilingualism": "Humanities>Languages & Literature",
    "language education/language acquisition": "Social Sciences>Educational Sciences",
    "languages & linguistics": "Humanities>Languages & Literature",
    "languages and literature": "Humanities>Languages & Literature",
    "law": "Social Sciences>Law",
    "leadership/industrial and organizational psychology": "Social Sciences>Psychology",
    "legal & forensic medicine": "Medical & Health Sciences>Basic Medicine",
    "library science/academic publishing": "Natural Sciences>Computer & Information Sciences",
    "life skills/behavioural sciences": "Social Sciences>Psychology",
    "ligands/chemical bonding": "Natural Sciences>Chemical Sciences",
    "linguistics terminology/phonetics": "Humanities>Languages & Literature",
    "lipid disorders/cardiology": "Medical & Health Sciences>Other Medical Sciences",
    "liquid crystals/phase transitions": "Natural Sciences>Physical Sciences",
    "literary studies": "Humanities>Languages & Literature",
    "livestock/animal feed": "Agricultural Sciences>Other Agricultural Sciences",
    "livestock/dairy farming": "Agricultural Sciences>Animal & Dairy Sciences",
    "logic and statistics/mathematical and quantitative methods (economics)": "Natural Sciences>Mathematics",
    "logistics & transportation": "Social Sciences>Economics & Business",
    "luminescence/detectors": "Natural Sciences>Physical Sciences",
    "lung disorders/respiratory diseases principally affecting the interstitium": "Medical & Health Sciences>Other Medical Sciences",
    "machine learning/simulation": "Natural Sciences>Computer & Information Sciences",
    "machine learning/social info processing": "Natural Sciences>Computer & Information Sciences",
    "machining/machine tools": "Engineering & Technology>Other Engineering & Technology Sciences",
    "macroeconomics": "Social Sciences>Economics & Business",
    "magnetic resonance imaging/biomagnetics": "Medical & Health Sciences>Other Medical Sciences",
    "magnetism/types of magnets": "Natural Sciences>Physical Sciences",
    "maintenance/mechanical engineering": "Engineering & Technology>Mechanical Engineering",
    "malaria/plasmodium": "Medical & Health Sciences>Other Medical Sciences",
    "marine biology": "Natural Sciences>Biological Sciences",
    "marine biology & hydrobiology": "Natural Sciences>Biological Sciences",
    "maritime archaeology/underwater archaeology": "Social Sciences>Other Social Sciences",
    "maritime incidents/ship collision": "Engineering & Technology>Other Engineering & Technology Sciences",
    "marketing": "Social Sciences>Economics & Business",
    "marketing techniques/services marketing": "Social Sciences>Economics & Business",
    "mass spectrometry/chromatography": "Natural Sciences>Chemical Sciences",
    "materials": "Engineering & Technology>Materials Engineering",
    "materials engineering": "Engineering & Technology>Materials Engineering",
    "mathematical economics/business terms": "Social Sciences>Economics & Business",
    "mathematical optimization/evolutionary algorithms": "Natural Sciences>Mathematics",
    "mathematical physics": "Natural Sciences>Physical Sciences",
    "mathematical physics/theoretical physics": "Natural Sciences>Physical Sciences",
    "mathematics": "Natural Sciences>Mathematics",
    "mathematics education/educational psychology": "Social Sciences>Educational Sciences",
    "meat/types of food": "Agricultural Sciences>Other Agricultural Sciences",
    "mechanical engineering": "Engineering & Technology>Mechanical Engineering",
    "mechanical engineering & transports": "Engineering & Technology>Mechanical Engineering",
    "mechanical power control/auto parts": "Engineering & Technology>Other Engineering & Technology Sciences",
    "mechanical ventilation/respiratory therapy": "Medical & Health Sciences>Other Medical Sciences",
    "mechanical vibrations/applied mathematics": "Natural Sciences>Mathematics",
    "mechanical vibrations/earthquake engineering": "Engineering & Technology>Civil Engineering",
    "mechanisms (engineering)/machines": "Engineering & Technology>Mechanical Engineering",
    "media and communications": "Social Sciences>Media & Communications",
    "medical and health sciences": "Medical & Health Sciences",
    "medical emergencies/trauma types": "Medical & Health Sciences>Other Medical Sciences",
    "medical emergencies/traumatology": "Medical & Health Sciences>Other Medical Sciences",
    "medical engineering": "Engineering & Technology>Medical Engineering",
    "medical imaging/imaging": "Medical & Health Sciences>Other Medical Sciences",
    "medical imaging/medical physics": "Medical & Health Sciences>Other Medical Sciences",
    "medical informatics": "Natural Sciences>Computer & Information Sciences",
    "medical monitoring/telehealth": "Medical & Health Sciences>Other Medical Sciences",
    "medical terminology/patient": "Medical & Health Sciences>Other Medical Sciences",
    "medical ultrasonography/medical imaging": "Medical & Health Sciences>Other Medical Sciences",
    "medicinal & biomolecular chemistry": "Natural Sciences>Chemical Sciences",
    "membrane technology/gas technologies": "Engineering & Technology>Chemical Engineering",
    "membrane technology/water desalination": "Engineering & Technology>Environmental Engineering",
    "membrane technology/water technology": "Engineering & Technology>Environmental Engineering",
    "menstrual cycle/noninflammatory disorders of female genital tract": "Medical & Health Sciences>Other Medical Sciences",
    "merchandising/retailing": "Social Sciences>Economics & Business",
    "metallurgical processes/flotation processes": "Engineering & Technology>Other Engineering & Technology Sciences",
    "metamaterials/electromagnetism": "Natural Sciences>Physical Sciences",
    "meteorology & atmospheric sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "microbiology": "Natural Sciences>Biological Sciences",
    "microfluidics/biotechnology": "Engineering & Technology>Other Engineering & Technology Sciences",
    "mining & metallurgy": "Engineering & Technology>Materials Engineering",
    "model theory/artificial intelligence": "Natural Sciences>Computer & Information Sciences",
    "molecular biology/fluorescence": "Natural Sciences>Biological Sciences",
    "mood disorders": "Social Sciences>Psychology",
    "music": "Humanities>Arts",
    "mycology & parasitology": "Natural Sciences>Biological Sciences",
    "mycology/symbiosis": "Natural Sciences>Biological Sciences",
    "mycotoxins/building biology": "Medical & Health Sciences>Other Medical Sciences",
    "nano-technology": "Engineering & Technology",
    "nanoparticles/emerging technologies": "Engineering & Technology>Nanotechnology",
    "nanoscience & nanotechnology": "Engineering & Technology>Nanotechnology",
    "natural disasters/disaster management": "Natural Sciences>Earth & Related Environmental Sciences",
    "natural language processing/computational linguistics": "Natural Sciences>Computer & Information Sciences",
    "natural sciences": "Natural Sciences",
    "neonatology/preterm birth": "Medical & Health Sciences>Other Medical Sciences",
    "network performance/road traffic management": "Engineering & Technology>Other Engineering & Technology Sciences",
    "networking & telecommunications": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "neurology & neurosurgery": "Medical & Health Sciences>Clinical Medicine",
    "neurophysiology/computational neuroscience": "Natural Sciences>Biological Sciences",
    "neuropsychology/neuropsychological assessment": "Social Sciences>Psychology",
    "neurotrauma/spinal cord disorders": "Medical & Health Sciences>Other Medical Sciences",
    "neurotrauma/stroke": "Medical & Health Sciences>Other Medical Sciences",
    "news/journalism": "Social Sciences>Media & Communications",
    "nitrides/optical diodes": "Engineering & Technology>Other Engineering & Technology Sciences",
    "non-profit organizations/types of organization": "Social Sciences>Economics & Business",
    "nonlinear optics": "Natural Sciences>Physical Sciences",
    "nose disorders/audiology": "Medical & Health Sciences>Other Medical Sciences",
    "nuclear & particles physics": "Natural Sciences>Physical Sciences",
    "nuclear magnetic resonance/scientific techniques": "Natural Sciences>Physical Sciences",
    "nuclear medicine & medical imaging": "Medical & Health Sciences>Other Medical Sciences",
    "nuclear physics/binding energy": "Natural Sciences>Physical Sciences",
    "nuclear physics/nuclear chemistry": "Natural Sciences>Physical Sciences",
    "nuclear physics/star types": "Natural Sciences>Physical Sciences",
    "nuclear power reactor types/nuclear technology": "Engineering & Technology>Other Engineering & Technology Sciences",
    "numerical & computational mathematics": "Natural Sciences>Mathematics",
    "numerical differential equations/partial differential equations": "Natural Sciences>Mathematics",
    "nursing": "Medical & Health Sciences>Other Medical Sciences",
    "nutrition & dietetics": "Medical & Health Sciences>Health Sciences",
    "nutrition by type/dietary supplements": "Medical & Health Sciences>Other Medical Sciences",
    "obesity/bariatrics": "Medical & Health Sciences>Other Medical Sciences",
    "obstetrics & reproductive medicine": "Medical & Health Sciences>Basic Medicine",
    "occupational therapy/learning disabilities": "Medical & Health Sciences>Other Medical Sciences",
    "oceanographical terminology/biological oceanography": "Natural Sciences>Earth & Related Environmental Sciences",
    "oceanography": "Natural Sciences>Earth & Related Environmental Sciences",
    "oceanography/effects of climate change": "Natural Sciences>Earth & Related Environmental Sciences",
    "oncology & carcinogenesis": "Medical & Health Sciences>Clinical Medicine",
    "oncology/dog diseases": "Medical & Health Sciences>Other Medical Sciences",
    "oncology/infectious causes of cancer": "Medical & Health Sciences>Other Medical Sciences",
    "operating system technology/virtual machines": "Natural Sciences>Computer & Information Sciences",
    "operations research": "Engineering & Technology>Other Engineering & Technology Sciences",
    "ophthalmology & optometry": "Medical & Health Sciences>Clinical Medicine",
    "optics": "Natural Sciences>Physical Sciences",
    "optoelectronics & photonics": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "oral mucosal pathology/conditions of the mucous membranes": "Medical & Health Sciences>Other Medical Sciences",
    "ore deposits/gold": "Natural Sciences>Earth & Related Environmental Sciences",
    "organ transplantation/diseases of liver": "Medical & Health Sciences>Other Medical Sciences",
    "organ transplantation/transplantation medicine": "Medical & Health Sciences>Other Medical Sciences",
    "organic chemistry": "Natural Sciences>Chemical Sciences",
    "organic semiconductors/organic polymers": "Natural Sciences>Physical Sciences",
    "organizational behavior/industrial and organizational psychology": "Social Sciences>Psychology",
    "ornithology": "Natural Sciences>Biological Sciences",
    "orthopedic surgical procedures/implants (medicine)": "Medical & Health Sciences>Other Medical Sciences",
    "orthopedic surgical procedures/prosthetics": "Medical & Health Sciences>Other Medical Sciences",
    "orthopedics": "Medical & Health Sciences>Clinical Medicine",
    "osteopathies/skeletal system": "Medical & Health Sciences>Other Medical Sciences",
    "other agricultural sciences": "Agricultural Sciences>Other Agricultural Sciences",
    "other engineering and technologies": "Engineering & Technology>Other Engineering & Technology Sciences",
    "other medical science": "Medical & Health Sciences>Other Medical Sciences",
    "other social sciences": "Social Sciences>Other Social Sciences",
    "otorhinolaryngology": "Medical & Health Sciences>Clinical Medicine",
    "otorhinolaryngology/oral and maxillofacial surgery": "Medical & Health Sciences>Other Medical Sciences",
    "oxygen/human biology": "Medical & Health Sciences>Other Medical Sciences",
    "pain/chronic pain syndromes": "Medical & Health Sciences>Other Medical Sciences",
    "paleontology": "Natural Sciences>Biological Sciences",
    "parallel computing/computer memory": "Natural Sciences>Computer & Information Sciences",
    "paraphyletic groups/coral reefs": "Natural Sciences>Biological Sciences",
    "parenting/childhood": "Social Sciences>Sociology",
    "partial differential equations/dynamical systems": "Natural Sciences>Mathematics",
    "particle physics/bosons": "Natural Sciences>Physical Sciences",
    "pathology": "Medical & Health Sciences>Other Medical Sciences",
    "pathology of temporomandibular joints, muscles of mastication and associated structures/musculoskeletal disorders": "Medical & Health Sciences>Other Medical Sciences",
    "pediatric cancers/anatomical pathology": "Medical & Health Sciences>Other Medical Sciences",
    "pediatrics": "Medical & Health Sciences>Clinical Medicine",
    "pediatrics/biostatistics": "Medical & Health Sciences>Other Medical Sciences",
    "people in health professions/people working with animals": "Medical & Health Sciences>Other Medical Sciences",
    "perception/sensory systems": "Social Sciences>Psychology",
    "periodontal disorders/inflammations": "Medical & Health Sciences>Other Medical Sciences",
    "petroleum production/fossil fuels": "Natural Sciences>Earth & Related Environmental Sciences",
    "petroleum production/underwater diving physics": "Natural Sciences>Earth & Related Environmental Sciences",
    "petrology/barrages (dam)": "Engineering & Technology>Civil Engineering",
    "pharmaceutical industry/pharmacology": "Medical & Health Sciences>Other Medical Sciences",
    "pharmacokinetics/life sciences industry": "Medical & Health Sciences>Other Medical Sciences",
    "pharmacology & pharmacy": "Medical & Health Sciences>Basic Medicine",
    "pharmacy schools/pharmacy": "Medical & Health Sciences>Other Medical Sciences",
    "philosophical movements/philosophical schools and traditions": "Humanities>Philosophy, Ethics & Religion",
    "philosophy": "Humanities>Philosophy, Ethics & Religion",
    "philosophy, ethics and religion": "Humanities>Philosophy, Ethics & Religion",
    "photonics/integrated circuits": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "physical chemistry": "Natural Sciences>Physical Sciences",
    "physical exercise/strength training": "Medical & Health Sciences>Other Medical Sciences",
    "physical organic chemistry/cheminformatics": "Natural Sciences>Chemical Sciences",
    "physical sciences": "Natural Sciences>Physical Sciences",
    "physics beyond the standard model/quantum gravity": "Natural Sciences>Physical Sciences",
    "physiology": "Medical & Health Sciences>Basic Medicine",
    "plant biology & botany": "Natural Sciences>Biological Sciences",
    "plasma physics/astrophysics": "Natural Sciences>Physical Sciences",
    "plasma processing/plasma physics": "Engineering & Technology>Other Engineering & Technology Sciences",
    "plasmonics/metamaterials": "Natural Sciences>Physical Sciences",
    "plate tectonics/lithosphere": "Natural Sciences>Earth & Related Environmental Sciences",
    "pleistocene extinctions/pleistocene": "Natural Sciences>Biological Sciences",
    "political science": "Social Sciences>Political Sciences",
    "political science & public administration": "Social Sciences>Political Sciences",
    "political science terminology/computers": "Social Sciences>Political Sciences",
    "politics/comparative politics": "Social Sciences>Political Sciences",
    "pollination/angiosperms": "Natural Sciences>Biological Sciences",
    "pollination/beekeeping": "Agricultural Sciences>Animal & Dairy Sciences",
    "pollution/air pollution": "Natural Sciences>Earth & Related Environmental Sciences",
    "pollution/environmental effects of pesticides": "Natural Sciences>Earth & Related Environmental Sciences",
    "polymers": "Engineering & Technology>Materials Engineering",
    "polymers/materials science": "Engineering & Technology>Materials Engineering",
    "polyphenols/nutrition": "Medical & Health Sciences>Other Medical Sciences",
    "polyphenols/phytochemicals": "Medical & Health Sciences>Other Medical Sciences",
    "positive psychology/happiness": "Social Sciences>Psychology",
    "poultry farming/chickens": "Agricultural Sciences>Animal & Dairy Sciences",
    "powders/materials science": "Engineering & Technology>Materials Engineering",
    "power electronics/electric power conversion": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "primates of africa/tool-using mammals": "Natural Sciences>Biological Sciences",
    "promotion and marketing communications/online advertising": "Social Sciences>Media & Communications",
    "prostate cancer/male genital surgery": "Medical & Health Sciences>Other Medical Sciences",
    "proteins/proteomics": "Natural Sciences>Biological Sciences",
    "proteoglycan metabolism disorders/autosomal recessive disorders": "Medical & Health Sciences>Other Medical Sciences",
    "proton-pump inhibitors/world health organization essential medicines": "Medical & Health Sciences>Other Medical Sciences",
    "psidium/ficus": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "psychiatry": "Medical & Health Sciences>Other Medical Sciences",
    "psychoactive drugs/drug culture": "Social Sciences>Psychology",
    "psychoanalysis": "Social Sciences>Psychology",
    "psychoanalysis/freudian psychology": "Social Sciences>Psychology",
    "psychology and cognitive sciences": "Social Sciences>Psychology",
    "psychometrics/quality management": "Social Sciences>Psychology",
    "psychometrics/quantitative research": "Social Sciences>Psychology",
    "psychotherapies/cognitive behavioral therapy": "Social Sciences>Psychology",
    "puberty/adolescent medicine": "Medical & Health Sciences>Other Medical Sciences",
    "public health": "Medical & Health Sciences>Health Sciences",
    "quality management/empirical evidence": "Social Sciences>Psychology",
    "quantum field theory/renormalization group": "Natural Sciences>Physical Sciences",
    "quantum mechanics/quantum chemistry": "Natural Sciences>Physical Sciences",
    "radar/navigation": "Engineering & Technology>Other Engineering & Technology Sciences",
    "radiation therapy procedures/medical physics": "Medical & Health Sciences>Other Medical Sciences",
    "radioactivity/medicinal radiochemistry": "Medical & Health Sciences>Other Medical Sciences",
    "radioactivity/radiation": "Medical & Health Sciences>Other Medical Sciences",
    "radiobiology/radiation health effects": "Medical & Health Sciences>Other Medical Sciences",
    "radiology/image segmentation": "Medical & Health Sciences>Other Medical Sciences",
    "radiology/medical imaging": "Medical & Health Sciences>Other Medical Sciences",
    "rare diseases/cognitive disorders": "Medical & Health Sciences>Other Medical Sciences",
    "redox": "Natural Sciences>Chemical Sciences",
    "regulatory compliance/e-commerce": "Social Sciences>Economics & Business",
    "rehabilitation": "Medical & Health Sciences>Other Medical Sciences",
    "religions & theology": "Humanities>Philosophy, Ethics & Religion",
    "remote sensing/imaging": "Engineering & Technology>Other Engineering & Technology Sciences",
    "remote sensing/satellite imagery": "Engineering & Technology>Other Engineering & Technology Sciences",
    "renewable fuels/biofuels technology": "Engineering & Technology>Environmental Engineering",
    "respiratory diseases principally affecting the interstitium/pulmonary heart disease and diseases of pulmonary circulation": "Medical & Health Sciences>Other Medical Sciences",
    "respiratory system": "Medical & Health Sciences>Basic Medicine",
    "rheumatology/arthritis": "Medical & Health Sciences>Other Medical Sciences",
    "risk analysis/actuarial science": "Social Sciences>Economics & Business",
    "robotics/robots": "Engineering & Technology>Other Engineering & Technology Sciences",
    "rocket propulsion/rocket engines": "Engineering & Technology>Other Engineering & Technology Sciences",
    "routes of administration/drug delivery devices": "Medical & Health Sciences>Other Medical Sciences",
    "rural culture/welfare economics": "Social Sciences>Sociology",
    "sanitation/sewerage": "Engineering & Technology>Environmental Engineering",
    "sanitation/water pollution": "Engineering & Technology>Environmental Engineering",
    "science and technology studies/technology in society": "Social Sciences>Sociology",
    "science education/philosophy of education": "Social Sciences>Educational Sciences",
    "science studies": "Social Sciences",
    "scientific techniques/diffraction": "Natural Sciences>Physical Sciences",
    "seeds/plant reproduction": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "seismology/seismology measurement": "Natural Sciences>Earth & Related Environmental Sciences",
    "senescence/old age": "Medical & Health Sciences>Other Medical Sciences",
    "sensors/biosensors": "Engineering & Technology>Other Engineering & Technology Sciences",
    "sensors/particle detectors": "Engineering & Technology>Other Engineering & Technology Sciences",
    "services marketing/retailing": "Social Sciences>Economics & Business",
    "sex crimes/sexual abuse": "Social Sciences>Criminology",
    "sex positions/sexual acts": "Humanities>Other Humanities",
    "sexual acts/interpersonal relationships": "Social Sciences>Sociology",
    "sexual dysfunctions/human sexuality": "Medical & Health Sciences>Other Medical Sciences",
    "sexual health/epidemiology": "Medical & Health Sciences>Other Medical Sciences",
    "shoulder/injuries of shoulder and upper arm": "Medical & Health Sciences>Other Medical Sciences",
    "simple aromatic rings/aromatic bases": "Natural Sciences>Chemical Sciences",
    "simple aromatic rings/triazoles": "Natural Sciences>Chemical Sciences",
    "skin conditions resulting from physical factors": "Medical & Health Sciences>Other Medical Sciences",
    "sleep disorders/breathing abnormalities": "Medical & Health Sciences>Other Medical Sciences",
    "sleep disorders/sleep physiology": "Medical & Health Sciences>Other Medical Sciences",
    "social and economic geography": "Social Sciences>Social & Economic Geography",
    "social concepts/accountability": "Social Sciences>Sociology",
    "social gatherings/tourism": "Social Sciences>Sociology",
    "social media": "Social Sciences>Media & Communications",
    "social networks/social information processing": "Social Sciences>Sociology",
    "social philosophy/capitalism": "Humanities>Philosophy, Ethics & Religion",
    "social psychology": "Social Sciences>Psychology",
    "social sciences": "Social Sciences",
    "social sciences methods": "Social Sciences",
    "social work": "Social Sciences>Sociology",
    "sociological terminology/anthropology": "Social Sciences>Sociology",
    "sociology": "Social Sciences>Sociology",
    "software engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "software engineering/computer occupations": "Natural Sciences>Computer & Information Sciences",
    "soil/natural materials": "Natural Sciences>Earth & Related Environmental Sciences",
    "solar phenomena/atmospheric radiation": "Natural Sciences>Earth & Related Environmental Sciences",
    "solar system/comets": "Natural Sciences>Earth & Related Environmental Sciences",
    "solid mechanics/deformation (mechanics)": "Engineering & Technology>Mechanical Engineering",
    "solid mechanics/fracture mechanics": "Engineering & Technology>Mechanical Engineering",
    "sonar": "Engineering & Technology>Other Engineering & Technology Sciences",
    "special education/learning disabilities": "Social Sciences>Educational Sciences",
    "spectroscopy/infrared spectroscopy": "Natural Sciences>Physical Sciences",
    "spectroscopy/mechanical vibrations": "Natural Sciences>Physical Sciences",
    "spectroscopy/scientific techniques": "Natural Sciences>Physical Sciences",
    "speech-language pathology & audiology": "Humanities>Languages & Literature",
    "sport sciences": "Natural Sciences>Physical Sciences",
    "sport, leisure & tourism": "Social Sciences>Other Social Sciences",
    "sports injuries/overuse injuries": "Medical & Health Sciences>Other Medical Sciences",
    "statistical randomness": "Natural Sciences>Mathematics",
    "statistics & probability": "Natural Sciences>Mathematics",
    "steels/building materials": "Engineering & Technology>Materials Engineering",
    "stem cells/transplantation medicine": "Medical & Health Sciences>Other Medical Sciences",
    "stock market/financial markets": "Social Sciences>Economics & Business",
    "strategic, defence & security studies": "Social Sciences>Political Sciences",
    "string theory/physics beyond the standard model": "Natural Sciences>Physical Sciences",
    "stroke/vascular diseases": "Medical & Health Sciences>Other Medical Sciences",
    "structural engineering/civil engineering": "Engineering & Technology>Civil Engineering",
    "substance abuse": "Medical & Health Sciences>Other Medical Sciences",
    "substance-related disorders/substance dependence": "Medical & Health Sciences>Other Medical Sciences",
    "superconductors/high-temperature superconductors": "Natural Sciences>Physical Sciences",
    "supply chain management/business terms": "Social Sciences>Economics & Business",
    "surgery": "Medical & Health Sciences>Clinical Medicine",
    "sustainability/environmental social science concepts": "Natural Sciences>Earth & Related Environmental Sciences",
    "sustainable energy/electric power distribution": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "sustainable food system/agroecology": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "sustainable transport": "Engineering & Technology>Other Engineering & Technology Sciences",
    "sustainable urban planning/urban planning": "Engineering & Technology>Other Engineering & Technology Sciences",
    "syntax/generative syntax": "Humanities>Languages & Literature",
    "systems engineering/test equipment": "Engineering & Technology>Other Engineering & Technology Sciences",
    "systems thinking/urban planning": "Engineering & Technology>Other Engineering & Technology Sciences",
    "temperature/thermodynamics": "Natural Sciences>Physical Sciences",
    "theories of gravity/general relativity": "Natural Sciences>Physical Sciences",
    "thermoelectricity/heat transfer": "Engineering & Technology>Other Engineering & Technology Sciences",
    "thyroid disease/pancreatic cancer": "Medical & Health Sciences>Other Medical Sciences",
    "thyroid disease/thyroid": "Medical & Health Sciences>Other Medical Sciences",
    "tick-borne diseases/ticks": "Medical & Health Sciences>Other Medical Sciences",
    "ticks/tick-borne diseases": "Medical & Health Sciences>Other Medical Sciences",
    "tourism/hospitality management": "Social Sciences>Economics & Business",
    "toxicology": "Medical & Health Sciences>Basic Medicine",
    "transistor types": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "transition metals/cofactors": "Natural Sciences>Chemical Sciences",
    "tribology/lubricants": "Engineering & Technology>Mechanical Engineering",
    "tropical medicine": "Medical & Health Sciences>Clinical Medicine",
    "tuberculosis/health in africa": "Medical & Health Sciences>Other Medical Sciences",
    "tylenchida/agricultural pest nematodes": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "types of tourism/tourism": "Social Sciences>Economics & Business",
    "ubiquitous computing/artificial intelligence laboratories": "Natural Sciences>Computer & Information Sciences",
    "unary operations/critical phenomena": "Natural Sciences>Physical Sciences",
    "urban & regional planning": "Social Sciences>Educational Sciences",
    "urinary system/symptoms and signs: urinary system": "Medical & Health Sciences>Other Medical Sciences",
    "urological conditions/urinary incontinence": "Medical & Health Sciences>Other Medical Sciences",
    "urology & nephrology": "Medical & Health Sciences>Clinical Medicine",
    "vaccines": "Medical & Health Sciences>Other Medical Sciences",
    "vascular surgery/diseases of the aorta": "Medical & Health Sciences>Other Medical Sciences",
    "vegetables/crops": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "veterinary science": "Agricultural Sciences>Veterinary Sciences",
    "veterinary sciences": "Agricultural Sciences>Veterinary Sciences",
    "virology": "Medical & Health Sciences>Basic Medicine",
    "vision/stereoscopy": "Medical & Health Sciences>Other Medical Sciences",
    "visualization (graphics)/infographics": "Social Sciences>Media & Communications",
    "weeds/agricultural pests": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "welfare economics/government aid programs": "Social Sciences>Economics & Business",
    "wireless energy transfer/electric power distribution": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "wireless networking/history of radio": "Natural Sciences>Computer & Information Sciences",
    "wireless sensor network/wireless networking": "Natural Sciences>Computer & Information Sciences",
    "zoology": "Agricultural Sciences>Animal & Dairy Sciences",
}

# TODO: add dynamic mapping when PC will return proper facets from public API
sd_training_temp_mapping = {
    "agricultural_sciences": "Agricultural Sciences",
    "agricultural_sciences-agricultural_biotechnology": "Agricultural Sciences>Agricultural Biotechnology",
    "agricultural_sciences-agriculture_forestry_and_fisheries": "Agricultural Sciences>Agriculture, Forestry & Fisheries",
    "engineering_and_technology": "Engineering & Technology",
    "engineering_and_technology-chemical_engineering": "Engineering & Technology>Chemical Engineering",
    "engineering_and_technology-civil_engineering": "Engineering & Technology>Civil Engineering",
    "engineering_and_technology-electrical_electronic_and_information_engineering": "Engineering & Technology>Electrical, Electronic & Information Engineering",
    "engineering_and_technology-other_engineering_and_technology_sciences": "Engineering & Technology>Other Engineering & Technology Sciences",
    "generic": "Generic",
    "generic-generic": "Generic>Generic",
    "humanities": "Humanities",
    "humanities-history_and_archaeology": "Humanities>History & Archaeology",
    "humanities-languages_and_literature": "Humanities>Languages & Literature",
    "humanities-other_humanities": "Humanities>Other Humanities",
    "humanities-philosophy_ethics_and_religion": "Humanities>Philosophy, Ethics & Religion",
    "medical_and_health_sciences": "Medical & Health Sciences",
    "medical_and_health_sciences-basic_medicine": "Medical & Health Sciences>Basic Medicine",
    "medical_and_health_sciences-other_medical_sciences": "Medical & Health Sciences>Other Medical Sciences",
    "natural_sciences": "Natural Sciences",
    "natural_sciences-earth_and_related_environmental_sciences": "Natural Sciences>Earth & Related Environmental Sciences",
    "natural_sciences-physical_sciences": "Natural Sciences>Physical Sciences",
    "other": "Other",
    "other-other": "Other>Other",
}
