# pylint: disable=duplicate-code
"""Provider expected input schema"""

provider_input_schema = {
    "abbreviation": ["string"],
    "affiliations": ["array<string>"],
    "areas_of_activity": ["array<string>"],
    "catalogues": ["array<string>"],
    "certifications": ["array<string>"],
    "city": ["string"],
    "country": ["string"],
    "description": ["string"],
    "esfri_domains": ["array<string>"],
    "esfri_type": ["string"],
    "hosting_legal_entity": ["string"],
    "id": ["bigint"],
    "legal_entity": ["boolean"],
    "legal_status": ["string"],
    "meril_scientific_domains": ["array<string>"],
    "multimedia_urls": ["array<struct<name:string,url:string>>"],
    "name": ["string"],
    "national_roadmaps": ["array<string>"],
    "networks": ["array<string>"],
    "participating_countries": ["array<string>"],
    "pid": ["string"],
    "postal_code": ["string"],
    "provider_life_cycle_status": ["string"],
    "public_contacts": [
        "array<struct<contactable_id:bigint,contactable_type:string,created_at:string,email:string,first_name:string,id:bigint,last_name:string,organisation:string,phone:string,position:string,updated_at:string>>"
    ],
    "publication_date": ["string"],
    "region": ["string"],
    "scientific_domains": ["array<string>"],
    "slug": ["string"],
    "societal_grand_challenges": ["array<string>"],
    "street_name_and_number": ["string"],
    "structure_types": ["array<string>"],
    "tag_list": ["array<string>"],
    "updated_at": ["string"],
    "usage_counts_downloads": ["bigint"],
    "usage_counts_views": ["bigint"],
    "webpage_url": ["string"],
}
