# pylint: disable=duplicate-code
"""Service expected input schema"""

service_input_schema = {
    "abbreviation": ["string"],
    "access_modes": ["array<string>"],
    "access_policies_url": ["string"],
    "access_types": ["array<string>"],
    "activate_message": ["string"],
    "catalogues": ["array<string>"],
    "categories": ["array<string>"],
    "certifications": ["array<string>"],
    "changelog": ["array<string>"],
    "dedicated_for": ["array<string>"],
    "description": ["string"],
    "eosc_if": ["array<string>"],
    "funding_bodies": ["array<string>"],
    "funding_programs": ["array<string>"],
    "guidelines": ["array<string>"],
    "geographical_availabilities": ["array<string>"],
    "grant_project_names": ["array<string>"],
    "helpdesk_email": ["string"],
    "helpdesk_url": ["string"],
    "horizontal": ["boolean"],
    "id": ["bigint"],
    "language_availability": ["array<string>"],
    "last_update": ["string"],
    "life_cycle_status": ["string"],
    "maintenance_url": ["string"],
    "manual_url": ["string"],
    "multimedia_urls": ["array<struct<name:string,url:string>>", "array<string>"],
    "name": ["string"],
    "offers_count": ["bigint"],
    "open_source_technologies": ["array<string>"],
    "order_type": ["string"],
    "order_url": ["string"],
    "payment_model_url": ["string"],
    "phase": ["string"],
    "pid": ["string"],
    "platforms": ["array<string>"],
    "pricing_url": ["string"],
    "privacy_policy_url": ["string"],
    "providers": ["array<string>"],
    "public_contacts": [
        "array<struct<contactable_id:bigint,contactable_type:string,created_at:string,email:string,first_name:string,id:bigint,last_name:string,organisation:string,phone:string,position:string,updated_at:string>>"
    ],
    "publication_date": ["string"],
    "rating": ["string"],
    "related_platforms": ["array<string>"],
    "resource_geographic_locations": ["array<string>"],
    "resource_organisation": ["string"],
    "restrictions": ["string"],
    "scientific_domains": ["array<string>"],
    "security_contact_email": ["string"],
    "service_opinion_count": ["bigint"],
    "sla_url": ["string"],
    "slug": ["string"],
    "standards": ["array<string>"],
    "status": ["string"],
    "status_monitoring_url": ["string"],
    "synchronized_at": ["string"],
    "tag_list": ["array<string>"],
    "tagline": ["string"],
    "terms_of_use_url": ["string"],
    "training_information_url": ["string"],
    "trl": ["string"],
    "unified_categories": ["array<string>"],
    "updated_at": ["string"],
    "upstream_id": ["bigint", "string"],
    "usage_counts_downloads": ["bigint"],
    "usage_counts_views": ["bigint"],
    "use_cases_urls": ["array<struct<name:string,url:string>>", "array<string>"],
    "version": ["string"],
    "webpage_url": ["string"],
}
