name: Backend styles

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
        cache: 'pipenv'
    - name: Install dependencies
      run: pipenv sync --dev
      working-directory: ./backend
    - name: Check with black
      run: |
        pipenv run black --check alembic app tests
      working-directory: ./backend
    - name: Check with isort
      run: |
        pipenv run isort . --check --diff
      working-directory: ./backend
    - name: Lint with pylint
      run: |
        pipenv run pylint app tests
      working-directory: ./backend
