name: Release
on:
#  - workflow_dispatch
  push:
    branches:
      - auto-release

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read info
        id: tags
        shell: bash
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
#          version-file: './ui/package.json'
          release-count: 0
          output-file: 'false'
          skip-git-pull: 'false'
          git-branch: 'master'
#          fallback-version: '0.1.0'

          skip-commit: 'true'
          skip-version-file: 'true'
          create-summary: 'true'

          github-token: ${{ secrets.github_token }}