name: Styles

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: enabled
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Upgrade pip and install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv
      working-directory: ./backend
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ./backend/.venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('./backend/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv
    - name: Install dependencies
      run: pipenv sync --dev
      working-directory: ./backend
    - name: Check with black
      run: |
        pipenv run black --check alembic app tests
      working-directory: ./backend
    - name: Check with isort
      run: |
        pipenv run isort . --check --diff
      working-directory: ./backend
    - name: Lint with pylint
      run: |
        pipenv run pylint app tests
      working-directory: ./backend
