name: Styles

on: push

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv sync --dev
      working-directory: ./backend
    - name: Check with black
      run: |
        pipenv run black --check app tests
      working-directory: ./backend
    - name: Check with isort
      run: |
        pipenv run isort . --check --diff
      working-directory: ./backend
    - name: Lint with pylint
      run: |
        pipenv run pylint app tests
      working-directory: ./backend
