name: Test

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f dc-test.yml up -d
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
        cache: 'pipenv'
    - name: Install dependencies
      run: pipenv sync --dev
      working-directory: ./backend
    - name: Run tests
      run: pipenv run pytest
      working-directory: ./backend
      env:
        TESTING: 1
        SOLR_URL: http://localhost:8993/solr/
    - name: Containers logs
      if: always()
      run: docker-compose logs
    - name: Stop containers
      if: always()
      run: docker-compose -f dc-test.yml down
