on: workflow_dispatch

name: trigger-release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Git bot config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Merge changes from development to master
        run: |
          git checkout master
          git merge origin/development 
          git push
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          version-file: 'version.txt'
          release-type: simple
          package-name: release-please-action
          default-branch: master
