name: UI styles

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache web
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-web-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-web-
      - name: Install dependencies
        run: npm i
        working-directory: ./ui
      - name: Linter check
        run: npm run lint
        working-directory: ./ui
      - name: Prettier check
        run: npm run prettier:check
        working-directory: ./ui
